// The bridge between the Go server and the module it runs (DECISIONS 99,
// 102): what the server asks of the world halves, and what they say back.
// The server writes one Call and the module answers with any number of
// Reply, each one whole. Nothing here is a plugin's: a payload passes
// through unread, as it does on the wire.
//
// `bun run proto` generates Rust into crates/protocol and Go into
// server/internal/protocol/module. A change here is the two sides of one
// binary: the module is built into the server, so they never meet apart.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: planet/module/v1/module.proto

package module

import (
	protocol "github.com/sulram/planet/server/internal/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// What the server asks. One a call.
type Call struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Call:
	//
	//	*Call_Describe
	//	*Call_Start
	//	*Call_Op
	//	*Call_Gone
	Call          isCall_Call `protobuf_oneof:"call"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Call) Reset() {
	*x = Call{}
	mi := &file_planet_module_v1_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Call) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Call) ProtoMessage() {}

func (x *Call) ProtoReflect() protoreflect.Message {
	mi := &file_planet_module_v1_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Call.ProtoReflect.Descriptor instead.
func (*Call) Descriptor() ([]byte, []int) {
	return file_planet_module_v1_module_proto_rawDescGZIP(), []int{0}
}

func (x *Call) GetCall() isCall_Call {
	if x != nil {
		return x.Call
	}
	return nil
}

func (x *Call) GetDescribe() *Describe {
	if x != nil {
		if x, ok := x.Call.(*Call_Describe); ok {
			return x.Describe
		}
	}
	return nil
}

func (x *Call) GetStart() *Start {
	if x != nil {
		if x, ok := x.Call.(*Call_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *Call) GetOp() *Op {
	if x != nil {
		if x, ok := x.Call.(*Call_Op); ok {
			return x.Op
		}
	}
	return nil
}

func (x *Call) GetGone() *Gone {
	if x != nil {
		if x, ok := x.Call.(*Call_Gone); ok {
			return x.Gone
		}
	}
	return nil
}

type isCall_Call interface {
	isCall_Call()
}

type Call_Describe struct {
	Describe *Describe `protobuf:"bytes,1,opt,name=describe,proto3,oneof"`
}

type Call_Start struct {
	Start *Start `protobuf:"bytes,2,opt,name=start,proto3,oneof"`
}

type Call_Op struct {
	Op *Op `protobuf:"bytes,3,opt,name=op,proto3,oneof"`
}

type Call_Gone struct {
	Gone *Gone `protobuf:"bytes,4,opt,name=gone,proto3,oneof"`
}

func (*Call_Describe) isCall_Call() {}

func (*Call_Start) isCall_Call() {}

func (*Call_Op) isCall_Call() {}

func (*Call_Gone) isCall_Call() {}

// Asks what the module carries. Answered with one Statement.
type Describe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Describe) Reset() {
	*x = Describe{}
	mi := &file_planet_module_v1_module_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Describe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Describe) ProtoMessage() {}

func (x *Describe) ProtoReflect() protoreflect.Message {
	mi := &file_planet_module_v1_module_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Describe.ProtoReflect.Descriptor instead.
func (*Describe) Descriptor() ([]byte, []int) {
	return file_planet_module_v1_module_proto_rawDescGZIP(), []int{1}
}

// The world starts, or starts again after the module was replaced: its
// recipe is what the bodies are measured by.
type Start struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipe        *protocol.Recipe       `protobuf:"bytes,1,opt,name=recipe,proto3" json:"recipe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Start) Reset() {
	*x = Start{}
	mi := &file_planet_module_v1_module_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Start) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Start) ProtoMessage() {}

func (x *Start) ProtoReflect() protoreflect.Message {
	mi := &file_planet_module_v1_module_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Start.ProtoReflect.Descriptor instead.
func (*Start) Descriptor() ([]byte, []int) {
	return file_planet_module_v1_module_proto_rawDescGZIP(), []int{2}
}

func (x *Start) GetRecipe() *protocol.Recipe {
	if x != nil {
		return x.Recipe
	}
	return nil
}

// A session as a world half sees it.
type Who struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Session uint32                 `protobuf:"varint,1,opt,name=session,proto3" json:"session,omitempty"`
	// The account's id in mundos. Empty for a visitor.
	User string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	// What the person is called here.
	Name  string         `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Level protocol.Level `protobuf:"varint,4,opt,name=level,proto3,enum=planet.v1.Level" json:"level,omitempty"`
	// Absent until the session has said where it is.
	Stance        *protocol.Stance `protobuf:"bytes,5,opt,name=stance,proto3" json:"stance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Who) Reset() {
	*x = Who{}
	mi := &file_planet_module_v1_module_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Who) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Who) ProtoMessage() {}

func (x *Who) ProtoReflect() protoreflect.Message {
	mi := &file_planet_module_v1_module_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Who.ProtoReflect.Descriptor instead.
func (*Who) Descriptor() ([]byte, []int) {
	return file_planet_module_v1_module_proto_rawDescGZIP(), []int{3}
}

func (x *Who) GetSession() uint32 {
	if x != nil {
		return x.Session
	}
	return 0
}

func (x *Who) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Who) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Who) GetLevel() protocol.Level {
	if x != nil {
		return x.Level
	}
	return protocol.Level(0)
}

func (x *Who) GetStance() *protocol.Stance {
	if x != nil {
		return x.Stance
	}
	return nil
}

// An op the server let through: the plugin is on, the kind is one of its ops
// and the session's level may ask it. The room rides with it whole, so a
// call stands alone.
type Op struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Plugin  string                 `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Kind    string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Payload []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Who asks: one of `here`.
	Session uint32 `protobuf:"varint,4,opt,name=session,proto3" json:"session,omitempty"`
	// The moment, in milliseconds since the Unix epoch.
	NowMs uint64 `protobuf:"varint,5,opt,name=now_ms,json=nowMs,proto3" json:"now_ms,omitempty"`
	// Everyone in the world, the one who asks included.
	Here          []*Who `protobuf:"bytes,6,rep,name=here,proto3" json:"here,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Op) Reset() {
	*x = Op{}
	mi := &file_planet_module_v1_module_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Op) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Op) ProtoMessage() {}

func (x *Op) ProtoReflect() protoreflect.Message {
	mi := &file_planet_module_v1_module_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Op.ProtoReflect.Descriptor instead.
func (*Op) Descriptor() ([]byte, []int) {
	return file_planet_module_v1_module_proto_rawDescGZIP(), []int{4}
}

func (x *Op) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *Op) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Op) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Op) GetSession() uint32 {
	if x != nil {
		return x.Session
	}
	return 0
}

func (x *Op) GetNowMs() uint64 {
	if x != nil {
		return x.NowMs
	}
	return 0
}

func (x *Op) GetHere() []*Who {
	if x != nil {
		return x.Here
	}
	return nil
}

// A session left: what the plugin kept for it is dropped.
type Gone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugin        string                 `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Session       uint32                 `protobuf:"varint,2,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gone) Reset() {
	*x = Gone{}
	mi := &file_planet_module_v1_module_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gone) ProtoMessage() {}

func (x *Gone) ProtoReflect() protoreflect.Message {
	mi := &file_planet_module_v1_module_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gone.ProtoReflect.Descriptor instead.
func (*Gone) Descriptor() ([]byte, []int) {
	return file_planet_module_v1_module_proto_rawDescGZIP(), []int{5}
}

func (x *Gone) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *Gone) GetSession() uint32 {
	if x != nil {
		return x.Session
	}
	return 0
}

// What the module says back.
type Reply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Reply:
	//
	//	*Reply_Statement
	//	*Reply_Tell
	Reply         isReply_Reply `protobuf_oneof:"reply"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_planet_module_v1_module_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_planet_module_v1_module_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_planet_module_v1_module_proto_rawDescGZIP(), []int{6}
}

func (x *Reply) GetReply() isReply_Reply {
	if x != nil {
		return x.Reply
	}
	return nil
}

func (x *Reply) GetStatement() *Statement {
	if x != nil {
		if x, ok := x.Reply.(*Reply_Statement); ok {
			return x.Statement
		}
	}
	return nil
}

func (x *Reply) GetTell() *Tell {
	if x != nil {
		if x, ok := x.Reply.(*Reply_Tell); ok {
			return x.Tell
		}
	}
	return nil
}

type isReply_Reply interface {
	isReply_Reply()
}

type Reply_Statement struct {
	Statement *Statement `protobuf:"bytes,1,opt,name=statement,proto3,oneof"`
}

type Reply_Tell struct {
	Tell *Tell `protobuf:"bytes,2,opt,name=tell,proto3,oneof"`
}

func (*Reply_Statement) isReply_Reply() {}

func (*Reply_Tell) isReply_Reply() {}

// The plugins the module carries, in the order the config lists them.
type Statement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugins       []*Carried             `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Statement) Reset() {
	*x = Statement{}
	mi := &file_planet_module_v1_module_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Statement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statement) ProtoMessage() {}

func (x *Statement) ProtoReflect() protoreflect.Message {
	mi := &file_planet_module_v1_module_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statement.ProtoReflect.Descriptor instead.
func (*Statement) Descriptor() ([]byte, []int) {
	return file_planet_module_v1_module_proto_rawDescGZIP(), []int{7}
}

func (x *Statement) GetPlugins() []*Carried {
	if x != nil {
		return x.Plugins
	}
	return nil
}

// One plugin's world half.
type Carried struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The version of its wire and of its seam.
	Version uint32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// Whether a world starts with it on.
	On            bool       `protobuf:"varint,3,opt,name=on,proto3" json:"on,omitempty"`
	Ops           []*Offered `protobuf:"bytes,4,rep,name=ops,proto3" json:"ops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Carried) Reset() {
	*x = Carried{}
	mi := &file_planet_module_v1_module_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Carried) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Carried) ProtoMessage() {}

func (x *Carried) ProtoReflect() protoreflect.Message {
	mi := &file_planet_module_v1_module_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Carried.ProtoReflect.Descriptor instead.
func (*Carried) Descriptor() ([]byte, []int) {
	return file_planet_module_v1_module_proto_rawDescGZIP(), []int{8}
}

func (x *Carried) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Carried) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Carried) GetOn() bool {
	if x != nil {
		return x.On
	}
	return false
}

func (x *Carried) GetOps() []*Offered {
	if x != nil {
		return x.Ops
	}
	return nil
}

// One thing a session may ask of a plugin, and the least level that may.
type Offered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Level         protocol.Level         `protobuf:"varint,2,opt,name=level,proto3,enum=planet.v1.Level" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Offered) Reset() {
	*x = Offered{}
	mi := &file_planet_module_v1_module_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Offered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offered) ProtoMessage() {}

func (x *Offered) ProtoReflect() protoreflect.Message {
	mi := &file_planet_module_v1_module_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offered.ProtoReflect.Descriptor instead.
func (*Offered) Descriptor() ([]byte, []int) {
	return file_planet_module_v1_module_proto_rawDescGZIP(), []int{9}
}

func (x *Offered) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Offered) GetLevel() protocol.Level {
	if x != nil {
		return x.Level
	}
	return protocol.Level(0)
}

// One event of a plugin, for the sessions named.
type Tell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugin        string                 `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	To            []uint32               `protobuf:"varint,4,rep,packed,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tell) Reset() {
	*x = Tell{}
	mi := &file_planet_module_v1_module_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tell) ProtoMessage() {}

func (x *Tell) ProtoReflect() protoreflect.Message {
	mi := &file_planet_module_v1_module_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tell.ProtoReflect.Descriptor instead.
func (*Tell) Descriptor() ([]byte, []int) {
	return file_planet_module_v1_module_proto_rawDescGZIP(), []int{10}
}

func (x *Tell) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *Tell) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Tell) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Tell) GetTo() []uint32 {
	if x != nil {
		return x.To
	}
	return nil
}

var File_planet_module_v1_module_proto protoreflect.FileDescriptor

const file_planet_module_v1_module_proto_rawDesc = "" +
	"\n" +
	"\x1dplanet/module/v1/module.proto\x12\x10planet.module.v1\x1a\x15planet/v1/world.proto\"\xcf\x01\n" +
	"\x04Call\x128\n" +
	"\bdescribe\x18\x01 \x01(\v2\x1a.planet.module.v1.DescribeH\x00R\bdescribe\x12/\n" +
	"\x05start\x18\x02 \x01(\v2\x17.planet.module.v1.StartH\x00R\x05start\x12&\n" +
	"\x02op\x18\x03 \x01(\v2\x14.planet.module.v1.OpH\x00R\x02op\x12,\n" +
	"\x04gone\x18\x04 \x01(\v2\x16.planet.module.v1.GoneH\x00R\x04goneB\x06\n" +
	"\x04call\"\n" +
	"\n" +
	"\bDescribe\"2\n" +
	"\x05Start\x12)\n" +
	"\x06recipe\x18\x01 \x01(\v2\x11.planet.v1.RecipeR\x06recipe\"\x9a\x01\n" +
	"\x03Who\x12\x18\n" +
	"\asession\x18\x01 \x01(\rR\asession\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12&\n" +
	"\x05level\x18\x04 \x01(\x0e2\x10.planet.v1.LevelR\x05level\x12)\n" +
	"\x06stance\x18\x05 \x01(\v2\x11.planet.v1.StanceR\x06stance\"\xa6\x01\n" +
	"\x02Op\x12\x16\n" +
	"\x06plugin\x18\x01 \x01(\tR\x06plugin\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x18\n" +
	"\asession\x18\x04 \x01(\rR\asession\x12\x15\n" +
	"\x06now_ms\x18\x05 \x01(\x04R\x05nowMs\x12)\n" +
	"\x04here\x18\x06 \x03(\v2\x15.planet.module.v1.WhoR\x04here\"8\n" +
	"\x04Gone\x12\x16\n" +
	"\x06plugin\x18\x01 \x01(\tR\x06plugin\x12\x18\n" +
	"\asession\x18\x02 \x01(\rR\asession\"{\n" +
	"\x05Reply\x12;\n" +
	"\tstatement\x18\x01 \x01(\v2\x1b.planet.module.v1.StatementH\x00R\tstatement\x12,\n" +
	"\x04tell\x18\x02 \x01(\v2\x16.planet.module.v1.TellH\x00R\x04tellB\a\n" +
	"\x05reply\"@\n" +
	"\tStatement\x123\n" +
	"\aplugins\x18\x01 \x03(\v2\x19.planet.module.v1.CarriedR\aplugins\"t\n" +
	"\aCarried\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12\x0e\n" +
	"\x02on\x18\x03 \x01(\bR\x02on\x12+\n" +
	"\x03ops\x18\x04 \x03(\v2\x19.planet.module.v1.OfferedR\x03ops\"E\n" +
	"\aOffered\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12&\n" +
	"\x05level\x18\x02 \x01(\x0e2\x10.planet.v1.LevelR\x05level\"\\\n" +
	"\x04Tell\x12\x16\n" +
	"\x06plugin\x18\x01 \x01(\tR\x06plugin\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x0e\n" +
	"\x02to\x18\x04 \x03(\rR\x02toBAZ?github.com/sulram/planet/server/internal/protocol/module;moduleb\x06proto3"

var (
	file_planet_module_v1_module_proto_rawDescOnce sync.Once
	file_planet_module_v1_module_proto_rawDescData []byte
)

func file_planet_module_v1_module_proto_rawDescGZIP() []byte {
	file_planet_module_v1_module_proto_rawDescOnce.Do(func() {
		file_planet_module_v1_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_planet_module_v1_module_proto_rawDesc), len(file_planet_module_v1_module_proto_rawDesc)))
	})
	return file_planet_module_v1_module_proto_rawDescData
}

var file_planet_module_v1_module_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_planet_module_v1_module_proto_goTypes = []any{
	(*Call)(nil),            // 0: planet.module.v1.Call
	(*Describe)(nil),        // 1: planet.module.v1.Describe
	(*Start)(nil),           // 2: planet.module.v1.Start
	(*Who)(nil),             // 3: planet.module.v1.Who
	(*Op)(nil),              // 4: planet.module.v1.Op
	(*Gone)(nil),            // 5: planet.module.v1.Gone
	(*Reply)(nil),           // 6: planet.module.v1.Reply
	(*Statement)(nil),       // 7: planet.module.v1.Statement
	(*Carried)(nil),         // 8: planet.module.v1.Carried
	(*Offered)(nil),         // 9: planet.module.v1.Offered
	(*Tell)(nil),            // 10: planet.module.v1.Tell
	(*protocol.Recipe)(nil), // 11: planet.v1.Recipe
	(protocol.Level)(0),     // 12: planet.v1.Level
	(*protocol.Stance)(nil), // 13: planet.v1.Stance
}
var file_planet_module_v1_module_proto_depIdxs = []int32{
	1,  // 0: planet.module.v1.Call.describe:type_name -> planet.module.v1.Describe
	2,  // 1: planet.module.v1.Call.start:type_name -> planet.module.v1.Start
	4,  // 2: planet.module.v1.Call.op:type_name -> planet.module.v1.Op
	5,  // 3: planet.module.v1.Call.gone:type_name -> planet.module.v1.Gone
	11, // 4: planet.module.v1.Start.recipe:type_name -> planet.v1.Recipe
	12, // 5: planet.module.v1.Who.level:type_name -> planet.v1.Level
	13, // 6: planet.module.v1.Who.stance:type_name -> planet.v1.Stance
	3,  // 7: planet.module.v1.Op.here:type_name -> planet.module.v1.Who
	7,  // 8: planet.module.v1.Reply.statement:type_name -> planet.module.v1.Statement
	10, // 9: planet.module.v1.Reply.tell:type_name -> planet.module.v1.Tell
	8,  // 10: planet.module.v1.Statement.plugins:type_name -> planet.module.v1.Carried
	9,  // 11: planet.module.v1.Carried.ops:type_name -> planet.module.v1.Offered
	12, // 12: planet.module.v1.Offered.level:type_name -> planet.v1.Level
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_planet_module_v1_module_proto_init() }
func file_planet_module_v1_module_proto_init() {
	if File_planet_module_v1_module_proto != nil {
		return
	}
	file_planet_module_v1_module_proto_msgTypes[0].OneofWrappers = []any{
		(*Call_Describe)(nil),
		(*Call_Start)(nil),
		(*Call_Op)(nil),
		(*Call_Gone)(nil),
	}
	file_planet_module_v1_module_proto_msgTypes[6].OneofWrappers = []any{
		(*Reply_Statement)(nil),
		(*Reply_Tell)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_planet_module_v1_module_proto_rawDesc), len(file_planet_module_v1_module_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_planet_module_v1_module_proto_goTypes,
		DependencyIndexes: file_planet_module_v1_module_proto_depIdxs,
		MessageInfos:      file_planet_module_v1_module_proto_msgTypes,
	}.Build()
	File_planet_module_v1_module_proto = out.File
	file_planet_module_v1_module_proto_goTypes = nil
	file_planet_module_v1_module_proto_depIdxs = nil
}
