// The cells of a world on the wire (DECISIONS 106, 107, 110): what a client
// asks of them and what the world says of them, each the payload of an
// Envelope whose owner is `cells`.
//
// Up, the ops: `open`, `change`, `close`, `take_back`, `put_back`, `look`.
// Down, the events: `opened`, `changed`, `restored`, `seen`.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: planet/cells/v1/cells.proto

package cells

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Kind int32

const (
	Kind_KIND_UNSPECIFIED Kind = 0
	// Fills the air of a box with a paint.
	Kind_KIND_CREATE Kind = 1
	// Empties a box.
	Kind_KIND_DELETE Kind = 2
	// Repaints what is solid in a box.
	Kind_KIND_PAINT Kind = 3
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_CREATE",
		2: "KIND_DELETE",
		3: "KIND_PAINT",
	}
	Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_CREATE":      1,
		"KIND_DELETE":      2,
		"KIND_PAINT":       3,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_planet_cells_v1_cells_proto_enumTypes[0].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_planet_cells_v1_cells_proto_enumTypes[0]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_planet_cells_v1_cells_proto_rawDescGZIP(), []int{0}
}

// What cells are seated on: the frame their addresses are counted in. A
// sector of the planet, or a sector of the moon, counted on the moon's own
// grid. A union, so a ship with a room aboard is the next.
type Seat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Seat:
	//
	//	*Seat_Sector
	//	*Seat_Moon
	Seat          isSeat_Seat `protobuf_oneof:"seat"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seat) Reset() {
	*x = Seat{}
	mi := &file_planet_cells_v1_cells_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seat) ProtoMessage() {}

func (x *Seat) ProtoReflect() protoreflect.Message {
	mi := &file_planet_cells_v1_cells_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seat.ProtoReflect.Descriptor instead.
func (*Seat) Descriptor() ([]byte, []int) {
	return file_planet_cells_v1_cells_proto_rawDescGZIP(), []int{0}
}

func (x *Seat) GetSeat() isSeat_Seat {
	if x != nil {
		return x.Seat
	}
	return nil
}

func (x *Seat) GetSector() uint32 {
	if x != nil {
		if x, ok := x.Seat.(*Seat_Sector); ok {
			return x.Sector
		}
	}
	return 0
}

func (x *Seat) GetMoon() uint32 {
	if x != nil {
		if x, ok := x.Seat.(*Seat_Moon); ok {
			return x.Moon
		}
	}
	return 0
}

type isSeat_Seat interface {
	isSeat_Seat()
}

type Seat_Sector struct {
	Sector uint32 `protobuf:"varint,1,opt,name=sector,proto3,oneof"`
}

type Seat_Moon struct {
	Moon uint32 `protobuf:"varint,2,opt,name=moon,proto3,oneof"`
}

func (*Seat_Sector) isSeat_Seat() {}

func (*Seat_Moon) isSeat_Seat() {}

// One gesture: a kind over a box of cells, both corners in it.
type Gesture struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          Kind                   `protobuf:"varint,1,opt,name=kind,proto3,enum=planet.cells.v1.Kind" json:"kind,omitempty"`
	X0            int32                  `protobuf:"zigzag32,2,opt,name=x0,proto3" json:"x0,omitempty"`
	Y0            int32                  `protobuf:"zigzag32,3,opt,name=y0,proto3" json:"y0,omitempty"`
	Z0            int32                  `protobuf:"zigzag32,4,opt,name=z0,proto3" json:"z0,omitempty"`
	X1            int32                  `protobuf:"zigzag32,5,opt,name=x1,proto3" json:"x1,omitempty"`
	Y1            int32                  `protobuf:"zigzag32,6,opt,name=y1,proto3" json:"y1,omitempty"`
	Z1            int32                  `protobuf:"zigzag32,7,opt,name=z1,proto3" json:"z1,omitempty"`
	Paint         uint32                 `protobuf:"varint,8,opt,name=paint,proto3" json:"paint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gesture) Reset() {
	*x = Gesture{}
	mi := &file_planet_cells_v1_cells_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gesture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gesture) ProtoMessage() {}

func (x *Gesture) ProtoReflect() protoreflect.Message {
	mi := &file_planet_cells_v1_cells_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gesture.ProtoReflect.Descriptor instead.
func (*Gesture) Descriptor() ([]byte, []int) {
	return file_planet_cells_v1_cells_proto_rawDescGZIP(), []int{1}
}

func (x *Gesture) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_KIND_UNSPECIFIED
}

func (x *Gesture) GetX0() int32 {
	if x != nil {
		return x.X0
	}
	return 0
}

func (x *Gesture) GetY0() int32 {
	if x != nil {
		return x.Y0
	}
	return 0
}

func (x *Gesture) GetZ0() int32 {
	if x != nil {
		return x.Z0
	}
	return 0
}

func (x *Gesture) GetX1() int32 {
	if x != nil {
		return x.X1
	}
	return 0
}

func (x *Gesture) GetY1() int32 {
	if x != nil {
		return x.Y1
	}
	return 0
}

func (x *Gesture) GetZ1() int32 {
	if x != nil {
		return x.Z1
	}
	return 0
}

func (x *Gesture) GetPaint() uint32 {
	if x != nil {
		return x.Paint
	}
	return 0
}

// A volume as it stands over its plot: where its cells start and end, and
// how many changes it has taken. What the world keeps of it, less its cells.
type Stood struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	PlotX int32                  `protobuf:"zigzag32,1,opt,name=plot_x,json=plotX,proto3" json:"plot_x,omitempty"`
	PlotY int32                  `protobuf:"zigzag32,2,opt,name=plot_y,json=plotY,proto3" json:"plot_y,omitempty"`
	// The lowest cell it holds, and how many it holds above it.
	Low    int32  `protobuf:"zigzag32,3,opt,name=low,proto3" json:"low,omitempty"`
	Height uint32 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	// One more for each change that landed in it.
	Version       uint64 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stood) Reset() {
	*x = Stood{}
	mi := &file_planet_cells_v1_cells_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stood) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stood) ProtoMessage() {}

func (x *Stood) ProtoReflect() protoreflect.Message {
	mi := &file_planet_cells_v1_cells_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stood.ProtoReflect.Descriptor instead.
func (*Stood) Descriptor() ([]byte, []int) {
	return file_planet_cells_v1_cells_proto_rawDescGZIP(), []int{2}
}

func (x *Stood) GetPlotX() int32 {
	if x != nil {
		return x.PlotX
	}
	return 0
}

func (x *Stood) GetPlotY() int32 {
	if x != nil {
		return x.PlotY
	}
	return 0
}

func (x *Stood) GetLow() int32 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Stood) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Stood) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// `open`: opens the volume of the plot a column is on, where none stands.
// The world reads the ground under the plot and says where the volume
// starts and ends.
type Open struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Seat  *Seat                  `protobuf:"bytes,1,opt,name=seat,proto3" json:"seat,omitempty"`
	// The column asked from, in blocks of the sector.
	U             float64 `protobuf:"fixed64,2,opt,name=u,proto3" json:"u,omitempty"`
	V             float64 `protobuf:"fixed64,3,opt,name=v,proto3" json:"v,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Open) Reset() {
	*x = Open{}
	mi := &file_planet_cells_v1_cells_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Open) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Open) ProtoMessage() {}

func (x *Open) ProtoReflect() protoreflect.Message {
	mi := &file_planet_cells_v1_cells_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Open.ProtoReflect.Descriptor instead.
func (*Open) Descriptor() ([]byte, []int) {
	return file_planet_cells_v1_cells_proto_rawDescGZIP(), []int{3}
}

func (x *Open) GetSeat() *Seat {
	if x != nil {
		return x.Seat
	}
	return nil
}

func (x *Open) GetU() float64 {
	if x != nil {
		return x.U
	}
	return 0
}

func (x *Open) GetV() float64 {
	if x != nil {
		return x.V
	}
	return 0
}

// `change`: gestures applied as one change, taken back as one.
type Change struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seat          *Seat                  `protobuf:"bytes,1,opt,name=seat,proto3" json:"seat,omitempty"`
	Gestures      []*Gesture             `protobuf:"bytes,2,rep,name=gestures,proto3" json:"gestures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Change) Reset() {
	*x = Change{}
	mi := &file_planet_cells_v1_cells_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Change) ProtoMessage() {}

func (x *Change) ProtoReflect() protoreflect.Message {
	mi := &file_planet_cells_v1_cells_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Change.ProtoReflect.Descriptor instead.
func (*Change) Descriptor() ([]byte, []int) {
	return file_planet_cells_v1_cells_proto_rawDescGZIP(), []int{4}
}

func (x *Change) GetSeat() *Seat {
	if x != nil {
		return x.Seat
	}
	return nil
}

func (x *Change) GetGestures() []*Gesture {
	if x != nil {
		return x.Gestures
	}
	return nil
}

// `close`: closes the volume over a plot. What was built in it goes with it
// and the plot is nature again: a change of this session's, taken back as
// one. Everyone near is told with `seen`, the volume gone.
type Close struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seat          *Seat                  `protobuf:"bytes,1,opt,name=seat,proto3" json:"seat,omitempty"`
	PlotX         int32                  `protobuf:"zigzag32,2,opt,name=plot_x,json=plotX,proto3" json:"plot_x,omitempty"`
	PlotY         int32                  `protobuf:"zigzag32,3,opt,name=plot_y,json=plotY,proto3" json:"plot_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Close) Reset() {
	*x = Close{}
	mi := &file_planet_cells_v1_cells_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Close) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Close) ProtoMessage() {}

func (x *Close) ProtoReflect() protoreflect.Message {
	mi := &file_planet_cells_v1_cells_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Close.ProtoReflect.Descriptor instead.
func (*Close) Descriptor() ([]byte, []int) {
	return file_planet_cells_v1_cells_proto_rawDescGZIP(), []int{5}
}

func (x *Close) GetSeat() *Seat {
	if x != nil {
		return x.Seat
	}
	return nil
}

func (x *Close) GetPlotX() int32 {
	if x != nil {
		return x.PlotX
	}
	return 0
}

func (x *Close) GetPlotY() int32 {
	if x != nil {
		return x.PlotY
	}
	return 0
}

// `take_back`: takes back the last change of this session that landed.
type TakeBack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TakeBack) Reset() {
	*x = TakeBack{}
	mi := &file_planet_cells_v1_cells_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeBack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeBack) ProtoMessage() {}

func (x *TakeBack) ProtoReflect() protoreflect.Message {
	mi := &file_planet_cells_v1_cells_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeBack.ProtoReflect.Descriptor instead.
func (*TakeBack) Descriptor() ([]byte, []int) {
	return file_planet_cells_v1_cells_proto_rawDescGZIP(), []int{6}
}

// `put_back`: puts back the last change this session took back.
type PutBack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutBack) Reset() {
	*x = PutBack{}
	mi := &file_planet_cells_v1_cells_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutBack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutBack) ProtoMessage() {}

func (x *PutBack) ProtoReflect() protoreflect.Message {
	mi := &file_planet_cells_v1_cells_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutBack.ProtoReflect.Descriptor instead.
func (*PutBack) Descriptor() ([]byte, []int) {
	return file_planet_cells_v1_cells_proto_rawDescGZIP(), []int{7}
}

// `look`: what this client holds of the volumes near it. The world answers
// with `seen`.
type Look struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Held          []*Held                `protobuf:"bytes,1,rep,name=held,proto3" json:"held,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Look) Reset() {
	*x = Look{}
	mi := &file_planet_cells_v1_cells_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Look) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Look) ProtoMessage() {}

func (x *Look) ProtoReflect() protoreflect.Message {
	mi := &file_planet_cells_v1_cells_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Look.ProtoReflect.Descriptor instead.
func (*Look) Descriptor() ([]byte, []int) {
	return file_planet_cells_v1_cells_proto_rawDescGZIP(), []int{8}
}

func (x *Look) GetHeld() []*Held {
	if x != nil {
		return x.Held
	}
	return nil
}

// A volume a client holds, at the version it holds it: whole, or as it is
// seen from afar.
type Held struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Seat    *Seat                  `protobuf:"bytes,1,opt,name=seat,proto3" json:"seat,omitempty"`
	PlotX   int32                  `protobuf:"zigzag32,2,opt,name=plot_x,json=plotX,proto3" json:"plot_x,omitempty"`
	PlotY   int32                  `protobuf:"zigzag32,3,opt,name=plot_y,json=plotY,proto3" json:"plot_y,omitempty"`
	Version uint64                 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	// Cells of the volume along each side of a cell held afar: 4 or 16. 0,
	// held whole.
	Afar          uint32 `protobuf:"varint,5,opt,name=afar,proto3" json:"afar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Held) Reset() {
	*x = Held{}
	mi := &file_planet_cells_v1_cells_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Held) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Held) ProtoMessage() {}

func (x *Held) ProtoReflect() protoreflect.Message {
	mi := &file_planet_cells_v1_cells_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Held.ProtoReflect.Descriptor instead.
func (*Held) Descriptor() ([]byte, []int) {
	return file_planet_cells_v1_cells_proto_rawDescGZIP(), []int{9}
}

func (x *Held) GetSeat() *Seat {
	if x != nil {
		return x.Seat
	}
	return nil
}

func (x *Held) GetPlotX() int32 {
	if x != nil {
		return x.PlotX
	}
	return 0
}

func (x *Held) GetPlotY() int32 {
	if x != nil {
		return x.PlotY
	}
	return 0
}

func (x *Held) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Held) GetAfar() uint32 {
	if x != nil {
		return x.Afar
	}
	return 0
}

// `opened`: a volume was opened, to everyone near it.
type Opened struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seat          *Seat                  `protobuf:"bytes,1,opt,name=seat,proto3" json:"seat,omitempty"`
	Stood         *Stood                 `protobuf:"bytes,2,opt,name=stood,proto3" json:"stood,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Opened) Reset() {
	*x = Opened{}
	mi := &file_planet_cells_v1_cells_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Opened) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Opened) ProtoMessage() {}

func (x *Opened) ProtoReflect() protoreflect.Message {
	mi := &file_planet_cells_v1_cells_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Opened.ProtoReflect.Descriptor instead.
func (*Opened) Descriptor() ([]byte, []int) {
	return file_planet_cells_v1_cells_proto_rawDescGZIP(), []int{10}
}

func (x *Opened) GetSeat() *Seat {
	if x != nil {
		return x.Seat
	}
	return nil
}

func (x *Opened) GetStood() *Stood {
	if x != nil {
		return x.Stood
	}
	return nil
}

// `changed`: gestures landed, to everyone near them, the asker included.
type Changed struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Who asked.
	Session  uint32     `protobuf:"varint,1,opt,name=session,proto3" json:"session,omitempty"`
	Seat     *Seat      `protobuf:"bytes,2,opt,name=seat,proto3" json:"seat,omitempty"`
	Gestures []*Gesture `protobuf:"bytes,3,rep,name=gestures,proto3" json:"gestures,omitempty"`
	// The volumes they landed in, at the version each has now.
	Stood         []*Stood `protobuf:"bytes,4,rep,name=stood,proto3" json:"stood,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Changed) Reset() {
	*x = Changed{}
	mi := &file_planet_cells_v1_cells_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Changed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Changed) ProtoMessage() {}

func (x *Changed) ProtoReflect() protoreflect.Message {
	mi := &file_planet_cells_v1_cells_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Changed.ProtoReflect.Descriptor instead.
func (*Changed) Descriptor() ([]byte, []int) {
	return file_planet_cells_v1_cells_proto_rawDescGZIP(), []int{11}
}

func (x *Changed) GetSession() uint32 {
	if x != nil {
		return x.Session
	}
	return 0
}

func (x *Changed) GetSeat() *Seat {
	if x != nil {
		return x.Seat
	}
	return nil
}

func (x *Changed) GetGestures() []*Gesture {
	if x != nil {
		return x.Gestures
	}
	return nil
}

func (x *Changed) GetStood() []*Stood {
	if x != nil {
		return x.Stood
	}
	return nil
}

// `restored`: a change was taken back or put back, to everyone near it: the
// cells of a box as they are now.
type Restored struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Session uint32                 `protobuf:"varint,1,opt,name=session,proto3" json:"session,omitempty"`
	Seat    *Seat                  `protobuf:"bytes,2,opt,name=seat,proto3" json:"seat,omitempty"`
	X0      int32                  `protobuf:"zigzag32,3,opt,name=x0,proto3" json:"x0,omitempty"`
	Y0      int32                  `protobuf:"zigzag32,4,opt,name=y0,proto3" json:"y0,omitempty"`
	Z0      int32                  `protobuf:"zigzag32,5,opt,name=z0,proto3" json:"z0,omitempty"`
	X1      int32                  `protobuf:"zigzag32,6,opt,name=x1,proto3" json:"x1,omitempty"`
	Y1      int32                  `protobuf:"zigzag32,7,opt,name=y1,proto3" json:"y1,omitempty"`
	Z1      int32                  `protobuf:"zigzag32,8,opt,name=z1,proto3" json:"z1,omitempty"`
	// The cells of the box, `x` fastest, then `y`, then `z`, packed.
	Cells         []byte   `protobuf:"bytes,9,opt,name=cells,proto3" json:"cells,omitempty"`
	Stood         []*Stood `protobuf:"bytes,10,rep,name=stood,proto3" json:"stood,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Restored) Reset() {
	*x = Restored{}
	mi := &file_planet_cells_v1_cells_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Restored) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Restored) ProtoMessage() {}

func (x *Restored) ProtoReflect() protoreflect.Message {
	mi := &file_planet_cells_v1_cells_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Restored.ProtoReflect.Descriptor instead.
func (*Restored) Descriptor() ([]byte, []int) {
	return file_planet_cells_v1_cells_proto_rawDescGZIP(), []int{12}
}

func (x *Restored) GetSession() uint32 {
	if x != nil {
		return x.Session
	}
	return 0
}

func (x *Restored) GetSeat() *Seat {
	if x != nil {
		return x.Seat
	}
	return nil
}

func (x *Restored) GetX0() int32 {
	if x != nil {
		return x.X0
	}
	return 0
}

func (x *Restored) GetY0() int32 {
	if x != nil {
		return x.Y0
	}
	return 0
}

func (x *Restored) GetZ0() int32 {
	if x != nil {
		return x.Z0
	}
	return 0
}

func (x *Restored) GetX1() int32 {
	if x != nil {
		return x.X1
	}
	return 0
}

func (x *Restored) GetY1() int32 {
	if x != nil {
		return x.Y1
	}
	return 0
}

func (x *Restored) GetZ1() int32 {
	if x != nil {
		return x.Z1
	}
	return 0
}

func (x *Restored) GetCells() []byte {
	if x != nil {
		return x.Cells
	}
	return nil
}

func (x *Restored) GetStood() []*Stood {
	if x != nil {
		return x.Stood
	}
	return nil
}

// The cells of one chunk, named by its lowest corner, packed.
type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"zigzag32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"zigzag32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             int32                  `protobuf:"zigzag32,3,opt,name=z,proto3" json:"z,omitempty"`
	Cells         []byte                 `protobuf:"bytes,4,opt,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_planet_cells_v1_cells_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_planet_cells_v1_cells_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_planet_cells_v1_cells_proto_rawDescGZIP(), []int{13}
}

func (x *Chunk) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Chunk) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Chunk) GetZ() int32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *Chunk) GetCells() []byte {
	if x != nil {
		return x.Cells
	}
	return nil
}

// A volume whole: where it stands and every chunk that holds something. Or,
// with `afar`, as it is seen from afar: the cells of each chunk a cell for
// every `afar` of them each way, solid where any is. At 4, 4 x 4 x 4 cells
// a chunk; at 16, one.
type Volume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seat          *Seat                  `protobuf:"bytes,1,opt,name=seat,proto3" json:"seat,omitempty"`
	Stood         *Stood                 `protobuf:"bytes,2,opt,name=stood,proto3" json:"stood,omitempty"`
	Chunks        []*Chunk               `protobuf:"bytes,3,rep,name=chunks,proto3" json:"chunks,omitempty"`
	Afar          uint32                 `protobuf:"varint,4,opt,name=afar,proto3" json:"afar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Volume) Reset() {
	*x = Volume{}
	mi := &file_planet_cells_v1_cells_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Volume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Volume) ProtoMessage() {}

func (x *Volume) ProtoReflect() protoreflect.Message {
	mi := &file_planet_cells_v1_cells_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Volume.ProtoReflect.Descriptor instead.
func (*Volume) Descriptor() ([]byte, []int) {
	return file_planet_cells_v1_cells_proto_rawDescGZIP(), []int{14}
}

func (x *Volume) GetSeat() *Seat {
	if x != nil {
		return x.Seat
	}
	return nil
}

func (x *Volume) GetStood() *Stood {
	if x != nil {
		return x.Stood
	}
	return nil
}

func (x *Volume) GetChunks() []*Chunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *Volume) GetAfar() uint32 {
	if x != nil {
		return x.Afar
	}
	return 0
}

// `seen`: volumes as they stand, and those that stand no more. The answer to
// `look`, of the volumes near the asker that it lacks or holds at another
// version: whole, and further off as they are seen from afar. And what
// everyone near is told when a volume is closed or stands again.
type Seen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volumes       []*Volume              `protobuf:"bytes,1,rep,name=volumes,proto3" json:"volumes,omitempty"`
	Gone          []*Held                `protobuf:"bytes,2,rep,name=gone,proto3" json:"gone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seen) Reset() {
	*x = Seen{}
	mi := &file_planet_cells_v1_cells_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seen) ProtoMessage() {}

func (x *Seen) ProtoReflect() protoreflect.Message {
	mi := &file_planet_cells_v1_cells_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seen.ProtoReflect.Descriptor instead.
func (*Seen) Descriptor() ([]byte, []int) {
	return file_planet_cells_v1_cells_proto_rawDescGZIP(), []int{15}
}

func (x *Seen) GetVolumes() []*Volume {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *Seen) GetGone() []*Held {
	if x != nil {
		return x.Gone
	}
	return nil
}

var File_planet_cells_v1_cells_proto protoreflect.FileDescriptor

const file_planet_cells_v1_cells_proto_rawDesc = "" +
	"\n" +
	"\x1bplanet/cells/v1/cells.proto\x12\x0fplanet.cells.v1\">\n" +
	"\x04Seat\x12\x18\n" +
	"\x06sector\x18\x01 \x01(\rH\x00R\x06sector\x12\x14\n" +
	"\x04moon\x18\x02 \x01(\rH\x00R\x04moonB\x06\n" +
	"\x04seat\"\xaa\x01\n" +
	"\aGesture\x12)\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x15.planet.cells.v1.KindR\x04kind\x12\x0e\n" +
	"\x02x0\x18\x02 \x01(\x11R\x02x0\x12\x0e\n" +
	"\x02y0\x18\x03 \x01(\x11R\x02y0\x12\x0e\n" +
	"\x02z0\x18\x04 \x01(\x11R\x02z0\x12\x0e\n" +
	"\x02x1\x18\x05 \x01(\x11R\x02x1\x12\x0e\n" +
	"\x02y1\x18\x06 \x01(\x11R\x02y1\x12\x0e\n" +
	"\x02z1\x18\a \x01(\x11R\x02z1\x12\x14\n" +
	"\x05paint\x18\b \x01(\rR\x05paint\"y\n" +
	"\x05Stood\x12\x15\n" +
	"\x06plot_x\x18\x01 \x01(\x11R\x05plotX\x12\x15\n" +
	"\x06plot_y\x18\x02 \x01(\x11R\x05plotY\x12\x10\n" +
	"\x03low\x18\x03 \x01(\x11R\x03low\x12\x16\n" +
	"\x06height\x18\x04 \x01(\rR\x06height\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x04R\aversion\"M\n" +
	"\x04Open\x12)\n" +
	"\x04seat\x18\x01 \x01(\v2\x15.planet.cells.v1.SeatR\x04seat\x12\f\n" +
	"\x01u\x18\x02 \x01(\x01R\x01u\x12\f\n" +
	"\x01v\x18\x03 \x01(\x01R\x01v\"i\n" +
	"\x06Change\x12)\n" +
	"\x04seat\x18\x01 \x01(\v2\x15.planet.cells.v1.SeatR\x04seat\x124\n" +
	"\bgestures\x18\x02 \x03(\v2\x18.planet.cells.v1.GestureR\bgestures\"`\n" +
	"\x05Close\x12)\n" +
	"\x04seat\x18\x01 \x01(\v2\x15.planet.cells.v1.SeatR\x04seat\x12\x15\n" +
	"\x06plot_x\x18\x02 \x01(\x11R\x05plotX\x12\x15\n" +
	"\x06plot_y\x18\x03 \x01(\x11R\x05plotY\"\n" +
	"\n" +
	"\bTakeBack\"\t\n" +
	"\aPutBack\"1\n" +
	"\x04Look\x12)\n" +
	"\x04held\x18\x01 \x03(\v2\x15.planet.cells.v1.HeldR\x04held\"\x8d\x01\n" +
	"\x04Held\x12)\n" +
	"\x04seat\x18\x01 \x01(\v2\x15.planet.cells.v1.SeatR\x04seat\x12\x15\n" +
	"\x06plot_x\x18\x02 \x01(\x11R\x05plotX\x12\x15\n" +
	"\x06plot_y\x18\x03 \x01(\x11R\x05plotY\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x04R\aversion\x12\x12\n" +
	"\x04afar\x18\x05 \x01(\rR\x04afar\"a\n" +
	"\x06Opened\x12)\n" +
	"\x04seat\x18\x01 \x01(\v2\x15.planet.cells.v1.SeatR\x04seat\x12,\n" +
	"\x05stood\x18\x02 \x01(\v2\x16.planet.cells.v1.StoodR\x05stood\"\xb2\x01\n" +
	"\aChanged\x12\x18\n" +
	"\asession\x18\x01 \x01(\rR\asession\x12)\n" +
	"\x04seat\x18\x02 \x01(\v2\x15.planet.cells.v1.SeatR\x04seat\x124\n" +
	"\bgestures\x18\x03 \x03(\v2\x18.planet.cells.v1.GestureR\bgestures\x12,\n" +
	"\x05stood\x18\x04 \x03(\v2\x16.planet.cells.v1.StoodR\x05stood\"\xf3\x01\n" +
	"\bRestored\x12\x18\n" +
	"\asession\x18\x01 \x01(\rR\asession\x12)\n" +
	"\x04seat\x18\x02 \x01(\v2\x15.planet.cells.v1.SeatR\x04seat\x12\x0e\n" +
	"\x02x0\x18\x03 \x01(\x11R\x02x0\x12\x0e\n" +
	"\x02y0\x18\x04 \x01(\x11R\x02y0\x12\x0e\n" +
	"\x02z0\x18\x05 \x01(\x11R\x02z0\x12\x0e\n" +
	"\x02x1\x18\x06 \x01(\x11R\x02x1\x12\x0e\n" +
	"\x02y1\x18\a \x01(\x11R\x02y1\x12\x0e\n" +
	"\x02z1\x18\b \x01(\x11R\x02z1\x12\x14\n" +
	"\x05cells\x18\t \x01(\fR\x05cells\x12,\n" +
	"\x05stood\x18\n" +
	" \x03(\v2\x16.planet.cells.v1.StoodR\x05stood\"G\n" +
	"\x05Chunk\x12\f\n" +
	"\x01x\x18\x01 \x01(\x11R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x11R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x11R\x01z\x12\x14\n" +
	"\x05cells\x18\x04 \x01(\fR\x05cells\"\xa5\x01\n" +
	"\x06Volume\x12)\n" +
	"\x04seat\x18\x01 \x01(\v2\x15.planet.cells.v1.SeatR\x04seat\x12,\n" +
	"\x05stood\x18\x02 \x01(\v2\x16.planet.cells.v1.StoodR\x05stood\x12.\n" +
	"\x06chunks\x18\x03 \x03(\v2\x16.planet.cells.v1.ChunkR\x06chunks\x12\x12\n" +
	"\x04afar\x18\x04 \x01(\rR\x04afar\"d\n" +
	"\x04Seen\x121\n" +
	"\avolumes\x18\x01 \x03(\v2\x17.planet.cells.v1.VolumeR\avolumes\x12)\n" +
	"\x04gone\x18\x02 \x03(\v2\x15.planet.cells.v1.HeldR\x04gone*N\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vKIND_CREATE\x10\x01\x12\x0f\n" +
	"\vKIND_DELETE\x10\x02\x12\x0e\n" +
	"\n" +
	"KIND_PAINT\x10\x03B?Z=github.com/sulram/planet/server/internal/protocol/cells;cellsb\x06proto3"

var (
	file_planet_cells_v1_cells_proto_rawDescOnce sync.Once
	file_planet_cells_v1_cells_proto_rawDescData []byte
)

func file_planet_cells_v1_cells_proto_rawDescGZIP() []byte {
	file_planet_cells_v1_cells_proto_rawDescOnce.Do(func() {
		file_planet_cells_v1_cells_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_planet_cells_v1_cells_proto_rawDesc), len(file_planet_cells_v1_cells_proto_rawDesc)))
	})
	return file_planet_cells_v1_cells_proto_rawDescData
}

var file_planet_cells_v1_cells_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_planet_cells_v1_cells_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_planet_cells_v1_cells_proto_goTypes = []any{
	(Kind)(0),        // 0: planet.cells.v1.Kind
	(*Seat)(nil),     // 1: planet.cells.v1.Seat
	(*Gesture)(nil),  // 2: planet.cells.v1.Gesture
	(*Stood)(nil),    // 3: planet.cells.v1.Stood
	(*Open)(nil),     // 4: planet.cells.v1.Open
	(*Change)(nil),   // 5: planet.cells.v1.Change
	(*Close)(nil),    // 6: planet.cells.v1.Close
	(*TakeBack)(nil), // 7: planet.cells.v1.TakeBack
	(*PutBack)(nil),  // 8: planet.cells.v1.PutBack
	(*Look)(nil),     // 9: planet.cells.v1.Look
	(*Held)(nil),     // 10: planet.cells.v1.Held
	(*Opened)(nil),   // 11: planet.cells.v1.Opened
	(*Changed)(nil),  // 12: planet.cells.v1.Changed
	(*Restored)(nil), // 13: planet.cells.v1.Restored
	(*Chunk)(nil),    // 14: planet.cells.v1.Chunk
	(*Volume)(nil),   // 15: planet.cells.v1.Volume
	(*Seen)(nil),     // 16: planet.cells.v1.Seen
}
var file_planet_cells_v1_cells_proto_depIdxs = []int32{
	0,  // 0: planet.cells.v1.Gesture.kind:type_name -> planet.cells.v1.Kind
	1,  // 1: planet.cells.v1.Open.seat:type_name -> planet.cells.v1.Seat
	1,  // 2: planet.cells.v1.Change.seat:type_name -> planet.cells.v1.Seat
	2,  // 3: planet.cells.v1.Change.gestures:type_name -> planet.cells.v1.Gesture
	1,  // 4: planet.cells.v1.Close.seat:type_name -> planet.cells.v1.Seat
	10, // 5: planet.cells.v1.Look.held:type_name -> planet.cells.v1.Held
	1,  // 6: planet.cells.v1.Held.seat:type_name -> planet.cells.v1.Seat
	1,  // 7: planet.cells.v1.Opened.seat:type_name -> planet.cells.v1.Seat
	3,  // 8: planet.cells.v1.Opened.stood:type_name -> planet.cells.v1.Stood
	1,  // 9: planet.cells.v1.Changed.seat:type_name -> planet.cells.v1.Seat
	2,  // 10: planet.cells.v1.Changed.gestures:type_name -> planet.cells.v1.Gesture
	3,  // 11: planet.cells.v1.Changed.stood:type_name -> planet.cells.v1.Stood
	1,  // 12: planet.cells.v1.Restored.seat:type_name -> planet.cells.v1.Seat
	3,  // 13: planet.cells.v1.Restored.stood:type_name -> planet.cells.v1.Stood
	1,  // 14: planet.cells.v1.Volume.seat:type_name -> planet.cells.v1.Seat
	3,  // 15: planet.cells.v1.Volume.stood:type_name -> planet.cells.v1.Stood
	14, // 16: planet.cells.v1.Volume.chunks:type_name -> planet.cells.v1.Chunk
	15, // 17: planet.cells.v1.Seen.volumes:type_name -> planet.cells.v1.Volume
	10, // 18: planet.cells.v1.Seen.gone:type_name -> planet.cells.v1.Held
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_planet_cells_v1_cells_proto_init() }
func file_planet_cells_v1_cells_proto_init() {
	if File_planet_cells_v1_cells_proto != nil {
		return
	}
	file_planet_cells_v1_cells_proto_msgTypes[0].OneofWrappers = []any{
		(*Seat_Sector)(nil),
		(*Seat_Moon)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_planet_cells_v1_cells_proto_rawDesc), len(file_planet_cells_v1_cells_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_planet_cells_v1_cells_proto_goTypes,
		DependencyIndexes: file_planet_cells_v1_cells_proto_depIdxs,
		EnumInfos:         file_planet_cells_v1_cells_proto_enumTypes,
		MessageInfos:      file_planet_cells_v1_cells_proto_msgTypes,
	}.Build()
	File_planet_cells_v1_cells_proto = out.File
	file_planet_cells_v1_cells_proto_goTypes = nil
	file_planet_cells_v1_cells_proto_depIdxs = nil
}
