// Code generated by `bun run plugins` from plugins.json. DO NOT EDIT.

// Package plugins is the plugins this version carries, in the order the
// config lists them (DECISIONS 88).
package plugins

import (
	"github.com/sulram/planet/server/internal/chat"
	"github.com/sulram/planet/server/internal/world"
)

// All is every plugin of the version, and whether a world starts with each
// on.
func All() []world.Installed {
	return []world.Installed{
		{Plugin: chat.New(), On: true},
	}
}
