//! The client halves of the plugins this version carries, in the order the
//! config lists them (DECISIONS 88). A shell plugs each one into its client.
//!
//! Generated by `bun run plugins` from plugins.json: edit the config, never
//! this file.

/// Every plugin of the version, ready to plug in.
pub fn all() -> Vec<Box<dyn client::Plugin>> {
    vec![chat_client::plugin(), build_client::plugin()]
}
