//! The world halves of the plugins this version carries, in the order the
//! config lists them, each with whether a world starts with it on
//! (DECISIONS 88, 99). The server's module hosts them.
//!
//! Generated by `bun run plugins` from plugins.json: edit the config, never
//! this file.

use world::Installed;

/// Every world half of the version, ready to host.
pub fn all() -> Vec<Installed> {
    vec![Installed {
        plugin: chat_world::plugin(),
        on: true,
    }]
}
