// The wire between a client and a world server. One message per WebSocket
// binary frame: a ClientMessage one way, a ServerMessage the other.
//
// The schema is the single source for Rust (crates/protocol) and Go
// (server/internal/protocol); `bun run proto` regenerates both. A change here
// that an older client cannot read bumps PROTOCOL in both, and Hello says
// which one a client speaks.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: planet/v1/world.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The body a stance is measured from. Every body is parametrised on the
// planet's sector grid: on the moon the column is the one its radial passes
// through, as the place code does it.
type Body int32

const (
	Body_BODY_PLANET Body = 0
	Body_BODY_MOON   Body = 1
)

// Enum value maps for Body.
var (
	Body_name = map[int32]string{
		0: "BODY_PLANET",
		1: "BODY_MOON",
	}
	Body_value = map[string]int32{
		"BODY_PLANET": 0,
		"BODY_MOON":   1,
	}
)

func (x Body) Enum() *Body {
	p := new(Body)
	*p = x
	return p
}

func (x Body) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Body) Descriptor() protoreflect.EnumDescriptor {
	return file_planet_v1_world_proto_enumTypes[0].Descriptor()
}

func (Body) Type() protoreflect.EnumType {
	return &file_planet_v1_world_proto_enumTypes[0]
}

func (x Body) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Body.Descriptor instead.
func (Body) EnumDescriptor() ([]byte, []int) {
	return file_planet_v1_world_proto_rawDescGZIP(), []int{0}
}

// How a body moves right now. One clip each, on every client.
type Gait int32

const (
	Gait_GAIT_IDLE Gait = 0
	Gait_GAIT_WALK Gait = 1
	Gait_GAIT_RUN  Gait = 2
	Gait_GAIT_JUMP Gait = 3
	Gait_GAIT_FALL Gait = 4
	Gait_GAIT_FLY  Gait = 5
	Gait_GAIT_SWIM Gait = 6
)

// Enum value maps for Gait.
var (
	Gait_name = map[int32]string{
		0: "GAIT_IDLE",
		1: "GAIT_WALK",
		2: "GAIT_RUN",
		3: "GAIT_JUMP",
		4: "GAIT_FALL",
		5: "GAIT_FLY",
		6: "GAIT_SWIM",
	}
	Gait_value = map[string]int32{
		"GAIT_IDLE": 0,
		"GAIT_WALK": 1,
		"GAIT_RUN":  2,
		"GAIT_JUMP": 3,
		"GAIT_FALL": 4,
		"GAIT_FLY":  5,
		"GAIT_SWIM": 6,
	}
)

func (x Gait) Enum() *Gait {
	p := new(Gait)
	*p = x
	return p
}

func (x Gait) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gait) Descriptor() protoreflect.EnumDescriptor {
	return file_planet_v1_world_proto_enumTypes[1].Descriptor()
}

func (Gait) Type() protoreflect.EnumType {
	return &file_planet_v1_world_proto_enumTypes[1]
}

func (x Gait) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gait.Descriptor instead.
func (Gait) EnumDescriptor() ([]byte, []int) {
	return file_planet_v1_world_proto_rawDescGZIP(), []int{1}
}

// Who hears a line.
type Scope int32

const (
	// Everyone within `NearBlocks` of the speaker, on the same body.
	Scope_SCOPE_NEAR Scope = 0
	// Everyone in the world, on every body.
	Scope_SCOPE_WORLD Scope = 1
)

// Enum value maps for Scope.
var (
	Scope_name = map[int32]string{
		0: "SCOPE_NEAR",
		1: "SCOPE_WORLD",
	}
	Scope_value = map[string]int32{
		"SCOPE_NEAR":  0,
		"SCOPE_WORLD": 1,
	}
)

func (x Scope) Enum() *Scope {
	p := new(Scope)
	*p = x
	return p
}

func (x Scope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Scope) Descriptor() protoreflect.EnumDescriptor {
	return file_planet_v1_world_proto_enumTypes[2].Descriptor()
}

func (Scope) Type() protoreflect.EnumType {
	return &file_planet_v1_world_proto_enumTypes[2]
}

func (x Scope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Scope.Descriptor instead.
func (Scope) EnumDescriptor() ([]byte, []int) {
	return file_planet_v1_world_proto_rawDescGZIP(), []int{2}
}

// What a session may do, as mundos says it for one entry. The order is the
// order of trust: a builder builds, an admin builds and founds the world.
type Level int32

const (
	Level_LEVEL_ANONYMOUS Level = 0
	Level_LEVEL_SIGNED_IN Level = 1
	Level_LEVEL_BUILDER   Level = 2
	Level_LEVEL_ADMIN     Level = 3
)

// Enum value maps for Level.
var (
	Level_name = map[int32]string{
		0: "LEVEL_ANONYMOUS",
		1: "LEVEL_SIGNED_IN",
		2: "LEVEL_BUILDER",
		3: "LEVEL_ADMIN",
	}
	Level_value = map[string]int32{
		"LEVEL_ANONYMOUS": 0,
		"LEVEL_SIGNED_IN": 1,
		"LEVEL_BUILDER":   2,
		"LEVEL_ADMIN":     3,
	}
)

func (x Level) Enum() *Level {
	p := new(Level)
	*p = x
	return p
}

func (x Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Level) Descriptor() protoreflect.EnumDescriptor {
	return file_planet_v1_world_proto_enumTypes[3].Descriptor()
}

func (Level) Type() protoreflect.EnumType {
	return &file_planet_v1_world_proto_enumTypes[3]
}

func (x Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Level.Descriptor instead.
func (Level) EnumDescriptor() ([]byte, []int) {
	return file_planet_v1_world_proto_rawDescGZIP(), []int{3}
}

// Where a body is and how it moves: what presence carries, many times a
// second. A pose is what a link carries; a stance is what a peer sends.
// The place is an address with fractional blocks, never a float position.
type Stance struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Body  Body                   `protobuf:"varint,1,opt,name=body,proto3,enum=planet.v1.Body" json:"body,omitempty"`
	// 0 to 5.
	Sector uint32 `protobuf:"varint,2,opt,name=sector,proto3" json:"sector,omitempty"`
	// Blocks along the sector's axes. A float holds a sector side of 2^16 to
	// 1/256 of a block, which is 2 mm.
	U float32 `protobuf:"fixed32,3,opt,name=u,proto3" json:"u,omitempty"`
	V float32 `protobuf:"fixed32,4,opt,name=v,proto3" json:"v,omitempty"`
	// Feet over the datum sphere of the body.
	HeightM float32 `protobuf:"fixed32,5,opt,name=height_m,json=heightM,proto3" json:"height_m,omitempty"`
	// Unit vector in world space, the way the body faces.
	FacingX float32 `protobuf:"fixed32,6,opt,name=facing_x,json=facingX,proto3" json:"facing_x,omitempty"`
	FacingY float32 `protobuf:"fixed32,7,opt,name=facing_y,json=facingY,proto3" json:"facing_y,omitempty"`
	FacingZ float32 `protobuf:"fixed32,8,opt,name=facing_z,json=facingZ,proto3" json:"facing_z,omitempty"`
	Gait    Gait    `protobuf:"varint,9,opt,name=gait,proto3,enum=planet.v1.Gait" json:"gait,omitempty"`
	// What the clip is played at: along the ground on foot, through the water
	// when swimming.
	SpeedMps float32 `protobuf:"fixed32,10,opt,name=speed_mps,json=speedMps,proto3" json:"speed_mps,omitempty"`
	// Running on foot, flying flat out.
	Sprint        bool `protobuf:"varint,11,opt,name=sprint,proto3" json:"sprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stance) Reset() {
	*x = Stance{}
	mi := &file_planet_v1_world_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stance) ProtoMessage() {}

func (x *Stance) ProtoReflect() protoreflect.Message {
	mi := &file_planet_v1_world_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stance.ProtoReflect.Descriptor instead.
func (*Stance) Descriptor() ([]byte, []int) {
	return file_planet_v1_world_proto_rawDescGZIP(), []int{0}
}

func (x *Stance) GetBody() Body {
	if x != nil {
		return x.Body
	}
	return Body_BODY_PLANET
}

func (x *Stance) GetSector() uint32 {
	if x != nil {
		return x.Sector
	}
	return 0
}

func (x *Stance) GetU() float32 {
	if x != nil {
		return x.U
	}
	return 0
}

func (x *Stance) GetV() float32 {
	if x != nil {
		return x.V
	}
	return 0
}

func (x *Stance) GetHeightM() float32 {
	if x != nil {
		return x.HeightM
	}
	return 0
}

func (x *Stance) GetFacingX() float32 {
	if x != nil {
		return x.FacingX
	}
	return 0
}

func (x *Stance) GetFacingY() float32 {
	if x != nil {
		return x.FacingY
	}
	return 0
}

func (x *Stance) GetFacingZ() float32 {
	if x != nil {
		return x.FacingZ
	}
	return 0
}

func (x *Stance) GetGait() Gait {
	if x != nil {
		return x.Gait
	}
	return Gait_GAIT_IDLE
}

func (x *Stance) GetSpeedMps() float32 {
	if x != nil {
		return x.SpeedMps
	}
	return 0
}

func (x *Stance) GetSprint() bool {
	if x != nil {
		return x.Sprint
	}
	return false
}

// What a client says first. Who it is was settled before: the key it was
// given on entering rides the socket URL, and no key is a visitor.
type Hello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The protocol this client speaks. Refused when it is not the server's.
	Protocol uint32 `protobuf:"varint,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// The avatar worn, as an asset reference: a path under the asset root, or
	// a URL. A person's own avatar loads through the same reference.
	Avatar string `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	// What to be called, at most `NameChars`. An account's name, as mundos
	// signed it, wins over it; a visitor is called this or nothing.
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_planet_v1_world_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_planet_v1_world_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_planet_v1_world_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *Hello) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Hello) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The avatar changed.
type Wear struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Avatar        string                 `protobuf:"bytes,1,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wear) Reset() {
	*x = Wear{}
	mi := &file_planet_v1_world_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wear) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wear) ProtoMessage() {}

func (x *Wear) ProtoReflect() protoreflect.Message {
	mi := &file_planet_v1_world_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wear.ProtoReflect.Descriptor instead.
func (*Wear) Descriptor() ([]byte, []int) {
	return file_planet_v1_world_proto_rawDescGZIP(), []int{2}
}

func (x *Wear) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

// The name changed. Empty is a name too: back to nobody in particular.
type Rename struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rename) Reset() {
	*x = Rename{}
	mi := &file_planet_v1_world_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rename) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rename) ProtoMessage() {}

func (x *Rename) ProtoReflect() protoreflect.Message {
	mi := &file_planet_v1_world_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rename.ProtoReflect.Descriptor instead.
func (*Rename) Descriptor() ([]byte, []int) {
	return file_planet_v1_world_proto_rawDescGZIP(), []int{3}
}

func (x *Rename) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// A line of chat. Relayed to everyone in scope, the speaker included, and
// never stored. Dropped, and nobody told, past the actor's length and rate
// limits: a UI holds the same limits so a person never meets them.
type Say struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Scope Scope                  `protobuf:"varint,1,opt,name=scope,proto3,enum=planet.v1.Scope" json:"scope,omitempty"`
	// At most 500 characters. May be empty when `here` is set.
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// Share where you stand: the server fills Said.stance from the stance it
	// holds, so a client cannot claim to stand where it does not.
	Here          bool `protobuf:"varint,3,opt,name=here,proto3" json:"here,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Say) Reset() {
	*x = Say{}
	mi := &file_planet_v1_world_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Say) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Say) ProtoMessage() {}

func (x *Say) ProtoReflect() protoreflect.Message {
	mi := &file_planet_v1_world_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Say.ProtoReflect.Descriptor instead.
func (*Say) Descriptor() ([]byte, []int) {
	return file_planet_v1_world_proto_rawDescGZIP(), []int{4}
}

func (x *Say) GetScope() Scope {
	if x != nil {
		return x.Scope
	}
	return Scope_SCOPE_NEAR
}

func (x *Say) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Say) GetHere() bool {
	if x != nil {
		return x.Here
	}
	return false
}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ClientMessage_Hello
	//	*ClientMessage_Stance
	//	*ClientMessage_Wear
	//	*ClientMessage_Say
	//	*ClientMessage_Rename
	Message       isClientMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_planet_v1_world_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_planet_v1_world_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_planet_v1_world_proto_rawDescGZIP(), []int{5}
}

func (x *ClientMessage) GetMessage() isClientMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ClientMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ClientMessage) GetStance() *Stance {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_Stance); ok {
			return x.Stance
		}
	}
	return nil
}

func (x *ClientMessage) GetWear() *Wear {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_Wear); ok {
			return x.Wear
		}
	}
	return nil
}

func (x *ClientMessage) GetSay() *Say {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_Say); ok {
			return x.Say
		}
	}
	return nil
}

func (x *ClientMessage) GetRename() *Rename {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_Rename); ok {
			return x.Rename
		}
	}
	return nil
}

type isClientMessage_Message interface {
	isClientMessage_Message()
}

type ClientMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ClientMessage_Stance struct {
	Stance *Stance `protobuf:"bytes,2,opt,name=stance,proto3,oneof"`
}

type ClientMessage_Wear struct {
	Wear *Wear `protobuf:"bytes,3,opt,name=wear,proto3,oneof"`
}

type ClientMessage_Say struct {
	Say *Say `protobuf:"bytes,4,opt,name=say,proto3,oneof"`
}

type ClientMessage_Rename struct {
	Rename *Rename `protobuf:"bytes,5,opt,name=rename,proto3,oneof"`
}

func (*ClientMessage_Hello) isClientMessage_Message() {}

func (*ClientMessage_Stance) isClientMessage_Message() {}

func (*ClientMessage_Wear) isClientMessage_Message() {}

func (*ClientMessage_Say) isClientMessage_Message() {}

func (*ClientMessage_Rename) isClientMessage_Message() {}

// Seed + params + generator version, as the world folder holds it. The
// params are the JSON the generator version owns.
type Recipe struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A u64 as 16 lowercase hex digits.
	Seed             string `protobuf:"bytes,1,opt,name=seed,proto3" json:"seed,omitempty"`
	GeneratorVersion uint32 `protobuf:"varint,2,opt,name=generator_version,json=generatorVersion,proto3" json:"generator_version,omitempty"`
	ParamsJson       string `protobuf:"bytes,3,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Recipe) Reset() {
	*x = Recipe{}
	mi := &file_planet_v1_world_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recipe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recipe) ProtoMessage() {}

func (x *Recipe) ProtoReflect() protoreflect.Message {
	mi := &file_planet_v1_world_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recipe.ProtoReflect.Descriptor instead.
func (*Recipe) Descriptor() ([]byte, []int) {
	return file_planet_v1_world_proto_rawDescGZIP(), []int{6}
}

func (x *Recipe) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

func (x *Recipe) GetGeneratorVersion() uint32 {
	if x != nil {
		return x.GeneratorVersion
	}
	return 0
}

func (x *Recipe) GetParamsJson() string {
	if x != nil {
		return x.ParamsJson
	}
	return ""
}

// Someone in the world.
type Peer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Given by the world actor, unique while the world is active.
	Session uint32 `protobuf:"varint,1,opt,name=session,proto3" json:"session,omitempty"`
	// As the person set it. Empty when they set none.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Signed out. Looks, never builds.
	Visitor bool   `protobuf:"varint,3,opt,name=visitor,proto3" json:"visitor,omitempty"`
	Avatar  string `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	// Absent until the peer has said where it is.
	Stance        *Stance `protobuf:"bytes,5,opt,name=stance,proto3" json:"stance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_planet_v1_world_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_planet_v1_world_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_planet_v1_world_proto_rawDescGZIP(), []int{7}
}

func (x *Peer) GetSession() uint32 {
	if x != nil {
		return x.Session
	}
	return 0
}

func (x *Peer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Peer) GetVisitor() bool {
	if x != nil {
		return x.Visitor
	}
	return false
}

func (x *Peer) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Peer) GetStance() *Stance {
	if x != nil {
		return x.Stance
	}
	return nil
}

// The answer to Hello: who you are here, what world this is, who is here.
type Welcome struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Session uint32                 `protobuf:"varint,1,opt,name=session,proto3" json:"session,omitempty"`
	Recipe  *Recipe                `protobuf:"bytes,2,opt,name=recipe,proto3" json:"recipe,omitempty"`
	Peers   []*Peer                `protobuf:"bytes,3,rep,name=peers,proto3" json:"peers,omitempty"`
	// What this session may do, for its life. A client offers its tools by it.
	Level         Level `protobuf:"varint,4,opt,name=level,proto3,enum=planet.v1.Level" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_planet_v1_world_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_planet_v1_world_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_planet_v1_world_proto_rawDescGZIP(), []int{8}
}

func (x *Welcome) GetSession() uint32 {
	if x != nil {
		return x.Session
	}
	return 0
}

func (x *Welcome) GetRecipe() *Recipe {
	if x != nil {
		return x.Recipe
	}
	return nil
}

func (x *Welcome) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *Welcome) GetLevel() Level {
	if x != nil {
		return x.Level
	}
	return Level_LEVEL_ANONYMOUS
}

type Joined struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          *Peer                  `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Joined) Reset() {
	*x = Joined{}
	mi := &file_planet_v1_world_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Joined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Joined) ProtoMessage() {}

func (x *Joined) ProtoReflect() protoreflect.Message {
	mi := &file_planet_v1_world_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Joined.ProtoReflect.Descriptor instead.
func (*Joined) Descriptor() ([]byte, []int) {
	return file_planet_v1_world_proto_rawDescGZIP(), []int{9}
}

func (x *Joined) GetPeer() *Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

type Left struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       uint32                 `protobuf:"varint,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Left) Reset() {
	*x = Left{}
	mi := &file_planet_v1_world_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Left) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Left) ProtoMessage() {}

func (x *Left) ProtoReflect() protoreflect.Message {
	mi := &file_planet_v1_world_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Left.ProtoReflect.Descriptor instead.
func (*Left) Descriptor() ([]byte, []int) {
	return file_planet_v1_world_proto_rawDescGZIP(), []int{10}
}

func (x *Left) GetSession() uint32 {
	if x != nil {
		return x.Session
	}
	return 0
}

type Wearing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       uint32                 `protobuf:"varint,1,opt,name=session,proto3" json:"session,omitempty"`
	Avatar        string                 `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wearing) Reset() {
	*x = Wearing{}
	mi := &file_planet_v1_world_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wearing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wearing) ProtoMessage() {}

func (x *Wearing) ProtoReflect() protoreflect.Message {
	mi := &file_planet_v1_world_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wearing.ProtoReflect.Descriptor instead.
func (*Wearing) Descriptor() ([]byte, []int) {
	return file_planet_v1_world_proto_rawDescGZIP(), []int{11}
}

func (x *Wearing) GetSession() uint32 {
	if x != nil {
		return x.Session
	}
	return 0
}

func (x *Wearing) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type Renamed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       uint32                 `protobuf:"varint,1,opt,name=session,proto3" json:"session,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Renamed) Reset() {
	*x = Renamed{}
	mi := &file_planet_v1_world_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Renamed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Renamed) ProtoMessage() {}

func (x *Renamed) ProtoReflect() protoreflect.Message {
	mi := &file_planet_v1_world_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Renamed.ProtoReflect.Descriptor instead.
func (*Renamed) Descriptor() ([]byte, []int) {
	return file_planet_v1_world_proto_rawDescGZIP(), []int{12}
}

func (x *Renamed) GetSession() uint32 {
	if x != nil {
		return x.Session
	}
	return 0
}

func (x *Renamed) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Moved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       uint32                 `protobuf:"varint,1,opt,name=session,proto3" json:"session,omitempty"`
	Stance        *Stance                `protobuf:"bytes,2,opt,name=stance,proto3" json:"stance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Moved) Reset() {
	*x = Moved{}
	mi := &file_planet_v1_world_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Moved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Moved) ProtoMessage() {}

func (x *Moved) ProtoReflect() protoreflect.Message {
	mi := &file_planet_v1_world_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Moved.ProtoReflect.Descriptor instead.
func (*Moved) Descriptor() ([]byte, []int) {
	return file_planet_v1_world_proto_rawDescGZIP(), []int{13}
}

func (x *Moved) GetSession() uint32 {
	if x != nil {
		return x.Session
	}
	return 0
}

func (x *Moved) GetStance() *Stance {
	if x != nil {
		return x.Stance
	}
	return nil
}

// Every stance that changed since the last tick, yours included: ignore your
// own session. Sent on every tick that has something to say, and every few
// seconds regardless, so a silent link is a dead one.
type Stances struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moved         []*Moved               `protobuf:"bytes,1,rep,name=moved,proto3" json:"moved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stances) Reset() {
	*x = Stances{}
	mi := &file_planet_v1_world_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stances) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stances) ProtoMessage() {}

func (x *Stances) ProtoReflect() protoreflect.Message {
	mi := &file_planet_v1_world_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stances.ProtoReflect.Descriptor instead.
func (*Stances) Descriptor() ([]byte, []int) {
	return file_planet_v1_world_proto_rawDescGZIP(), []int{14}
}

func (x *Stances) GetMoved() []*Moved {
	if x != nil {
		return x.Moved
	}
	return nil
}

// A line someone said, the receiver's own included.
type Said struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Session uint32                 `protobuf:"varint,1,opt,name=session,proto3" json:"session,omitempty"`
	Scope   Scope                  `protobuf:"varint,2,opt,name=scope,proto3,enum=planet.v1.Scope" json:"scope,omitempty"`
	Text    string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	// Where the speaker stood, when they shared it. Absent otherwise.
	Stance        *Stance `protobuf:"bytes,4,opt,name=stance,proto3" json:"stance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Said) Reset() {
	*x = Said{}
	mi := &file_planet_v1_world_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Said) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Said) ProtoMessage() {}

func (x *Said) ProtoReflect() protoreflect.Message {
	mi := &file_planet_v1_world_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Said.ProtoReflect.Descriptor instead.
func (*Said) Descriptor() ([]byte, []int) {
	return file_planet_v1_world_proto_rawDescGZIP(), []int{15}
}

func (x *Said) GetSession() uint32 {
	if x != nil {
		return x.Session
	}
	return 0
}

func (x *Said) GetScope() Scope {
	if x != nil {
		return x.Scope
	}
	return Scope_SCOPE_NEAR
}

func (x *Said) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Said) GetStance() *Stance {
	if x != nil {
		return x.Stance
	}
	return nil
}

// Sent instead of Welcome, then the socket closes.
type Refused struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Refused) Reset() {
	*x = Refused{}
	mi := &file_planet_v1_world_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Refused) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Refused) ProtoMessage() {}

func (x *Refused) ProtoReflect() protoreflect.Message {
	mi := &file_planet_v1_world_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Refused.ProtoReflect.Descriptor instead.
func (*Refused) Descriptor() ([]byte, []int) {
	return file_planet_v1_world_proto_rawDescGZIP(), []int{16}
}

func (x *Refused) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ServerMessage_Welcome
	//	*ServerMessage_Joined
	//	*ServerMessage_Left
	//	*ServerMessage_Stances
	//	*ServerMessage_Wearing
	//	*ServerMessage_Refused
	//	*ServerMessage_Said
	//	*ServerMessage_Renamed
	Message       isServerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_planet_v1_world_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_planet_v1_world_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_planet_v1_world_proto_rawDescGZIP(), []int{17}
}

func (x *ServerMessage) GetMessage() isServerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ServerMessage) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *ServerMessage) GetJoined() *Joined {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Joined); ok {
			return x.Joined
		}
	}
	return nil
}

func (x *ServerMessage) GetLeft() *Left {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Left); ok {
			return x.Left
		}
	}
	return nil
}

func (x *ServerMessage) GetStances() *Stances {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Stances); ok {
			return x.Stances
		}
	}
	return nil
}

func (x *ServerMessage) GetWearing() *Wearing {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Wearing); ok {
			return x.Wearing
		}
	}
	return nil
}

func (x *ServerMessage) GetRefused() *Refused {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Refused); ok {
			return x.Refused
		}
	}
	return nil
}

func (x *ServerMessage) GetSaid() *Said {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Said); ok {
			return x.Said
		}
	}
	return nil
}

func (x *ServerMessage) GetRenamed() *Renamed {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Renamed); ok {
			return x.Renamed
		}
	}
	return nil
}

type isServerMessage_Message interface {
	isServerMessage_Message()
}

type ServerMessage_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type ServerMessage_Joined struct {
	Joined *Joined `protobuf:"bytes,2,opt,name=joined,proto3,oneof"`
}

type ServerMessage_Left struct {
	Left *Left `protobuf:"bytes,3,opt,name=left,proto3,oneof"`
}

type ServerMessage_Stances struct {
	Stances *Stances `protobuf:"bytes,4,opt,name=stances,proto3,oneof"`
}

type ServerMessage_Wearing struct {
	Wearing *Wearing `protobuf:"bytes,5,opt,name=wearing,proto3,oneof"`
}

type ServerMessage_Refused struct {
	Refused *Refused `protobuf:"bytes,6,opt,name=refused,proto3,oneof"`
}

type ServerMessage_Said struct {
	Said *Said `protobuf:"bytes,7,opt,name=said,proto3,oneof"`
}

type ServerMessage_Renamed struct {
	Renamed *Renamed `protobuf:"bytes,8,opt,name=renamed,proto3,oneof"`
}

func (*ServerMessage_Welcome) isServerMessage_Message() {}

func (*ServerMessage_Joined) isServerMessage_Message() {}

func (*ServerMessage_Left) isServerMessage_Message() {}

func (*ServerMessage_Stances) isServerMessage_Message() {}

func (*ServerMessage_Wearing) isServerMessage_Message() {}

func (*ServerMessage_Refused) isServerMessage_Message() {}

func (*ServerMessage_Said) isServerMessage_Message() {}

func (*ServerMessage_Renamed) isServerMessage_Message() {}

var File_planet_v1_world_proto protoreflect.FileDescriptor

const file_planet_v1_world_proto_rawDesc = "" +
	"\n" +
	"\x15planet/v1/world.proto\x12\tplanet.v1\"\xa7\x02\n" +
	"\x06Stance\x12#\n" +
	"\x04body\x18\x01 \x01(\x0e2\x0f.planet.v1.BodyR\x04body\x12\x16\n" +
	"\x06sector\x18\x02 \x01(\rR\x06sector\x12\f\n" +
	"\x01u\x18\x03 \x01(\x02R\x01u\x12\f\n" +
	"\x01v\x18\x04 \x01(\x02R\x01v\x12\x19\n" +
	"\bheight_m\x18\x05 \x01(\x02R\aheightM\x12\x19\n" +
	"\bfacing_x\x18\x06 \x01(\x02R\afacingX\x12\x19\n" +
	"\bfacing_y\x18\a \x01(\x02R\afacingY\x12\x19\n" +
	"\bfacing_z\x18\b \x01(\x02R\afacingZ\x12#\n" +
	"\x04gait\x18\t \x01(\x0e2\x0f.planet.v1.GaitR\x04gait\x12\x1b\n" +
	"\tspeed_mps\x18\n" +
	" \x01(\x02R\bspeedMps\x12\x16\n" +
	"\x06sprint\x18\v \x01(\bR\x06sprint\"O\n" +
	"\x05Hello\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\rR\bprotocol\x12\x16\n" +
	"\x06avatar\x18\x02 \x01(\tR\x06avatar\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\x1e\n" +
	"\x04Wear\x12\x16\n" +
	"\x06avatar\x18\x01 \x01(\tR\x06avatar\"\x1c\n" +
	"\x06Rename\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"U\n" +
	"\x03Say\x12&\n" +
	"\x05scope\x18\x01 \x01(\x0e2\x10.planet.v1.ScopeR\x05scope\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x12\n" +
	"\x04here\x18\x03 \x01(\bR\x04here\"\xe9\x01\n" +
	"\rClientMessage\x12(\n" +
	"\x05hello\x18\x01 \x01(\v2\x10.planet.v1.HelloH\x00R\x05hello\x12+\n" +
	"\x06stance\x18\x02 \x01(\v2\x11.planet.v1.StanceH\x00R\x06stance\x12%\n" +
	"\x04wear\x18\x03 \x01(\v2\x0f.planet.v1.WearH\x00R\x04wear\x12\"\n" +
	"\x03say\x18\x04 \x01(\v2\x0e.planet.v1.SayH\x00R\x03say\x12+\n" +
	"\x06rename\x18\x05 \x01(\v2\x11.planet.v1.RenameH\x00R\x06renameB\t\n" +
	"\amessage\"j\n" +
	"\x06Recipe\x12\x12\n" +
	"\x04seed\x18\x01 \x01(\tR\x04seed\x12+\n" +
	"\x11generator_version\x18\x02 \x01(\rR\x10generatorVersion\x12\x1f\n" +
	"\vparams_json\x18\x03 \x01(\tR\n" +
	"paramsJson\"\x91\x01\n" +
	"\x04Peer\x12\x18\n" +
	"\asession\x18\x01 \x01(\rR\asession\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\avisitor\x18\x03 \x01(\bR\avisitor\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12)\n" +
	"\x06stance\x18\x05 \x01(\v2\x11.planet.v1.StanceR\x06stance\"\x9d\x01\n" +
	"\aWelcome\x12\x18\n" +
	"\asession\x18\x01 \x01(\rR\asession\x12)\n" +
	"\x06recipe\x18\x02 \x01(\v2\x11.planet.v1.RecipeR\x06recipe\x12%\n" +
	"\x05peers\x18\x03 \x03(\v2\x0f.planet.v1.PeerR\x05peers\x12&\n" +
	"\x05level\x18\x04 \x01(\x0e2\x10.planet.v1.LevelR\x05level\"-\n" +
	"\x06Joined\x12#\n" +
	"\x04peer\x18\x01 \x01(\v2\x0f.planet.v1.PeerR\x04peer\" \n" +
	"\x04Left\x12\x18\n" +
	"\asession\x18\x01 \x01(\rR\asession\";\n" +
	"\aWearing\x12\x18\n" +
	"\asession\x18\x01 \x01(\rR\asession\x12\x16\n" +
	"\x06avatar\x18\x02 \x01(\tR\x06avatar\"7\n" +
	"\aRenamed\x12\x18\n" +
	"\asession\x18\x01 \x01(\rR\asession\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"L\n" +
	"\x05Moved\x12\x18\n" +
	"\asession\x18\x01 \x01(\rR\asession\x12)\n" +
	"\x06stance\x18\x02 \x01(\v2\x11.planet.v1.StanceR\x06stance\"1\n" +
	"\aStances\x12&\n" +
	"\x05moved\x18\x01 \x03(\v2\x10.planet.v1.MovedR\x05moved\"\x87\x01\n" +
	"\x04Said\x12\x18\n" +
	"\asession\x18\x01 \x01(\rR\asession\x12&\n" +
	"\x05scope\x18\x02 \x01(\x0e2\x10.planet.v1.ScopeR\x05scope\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12)\n" +
	"\x06stance\x18\x04 \x01(\v2\x11.planet.v1.StanceR\x06stance\"!\n" +
	"\aRefused\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\x85\x03\n" +
	"\rServerMessage\x12.\n" +
	"\awelcome\x18\x01 \x01(\v2\x12.planet.v1.WelcomeH\x00R\awelcome\x12+\n" +
	"\x06joined\x18\x02 \x01(\v2\x11.planet.v1.JoinedH\x00R\x06joined\x12%\n" +
	"\x04left\x18\x03 \x01(\v2\x0f.planet.v1.LeftH\x00R\x04left\x12.\n" +
	"\astances\x18\x04 \x01(\v2\x12.planet.v1.StancesH\x00R\astances\x12.\n" +
	"\awearing\x18\x05 \x01(\v2\x12.planet.v1.WearingH\x00R\awearing\x12.\n" +
	"\arefused\x18\x06 \x01(\v2\x12.planet.v1.RefusedH\x00R\arefused\x12%\n" +
	"\x04said\x18\a \x01(\v2\x0f.planet.v1.SaidH\x00R\x04said\x12.\n" +
	"\arenamed\x18\b \x01(\v2\x12.planet.v1.RenamedH\x00R\arenamedB\t\n" +
	"\amessage*&\n" +
	"\x04Body\x12\x0f\n" +
	"\vBODY_PLANET\x10\x00\x12\r\n" +
	"\tBODY_MOON\x10\x01*m\n" +
	"\x04Gait\x12\r\n" +
	"\tGAIT_IDLE\x10\x00\x12\r\n" +
	"\tGAIT_WALK\x10\x01\x12\f\n" +
	"\bGAIT_RUN\x10\x02\x12\r\n" +
	"\tGAIT_JUMP\x10\x03\x12\r\n" +
	"\tGAIT_FALL\x10\x04\x12\f\n" +
	"\bGAIT_FLY\x10\x05\x12\r\n" +
	"\tGAIT_SWIM\x10\x06*(\n" +
	"\x05Scope\x12\x0e\n" +
	"\n" +
	"SCOPE_NEAR\x10\x00\x12\x0f\n" +
	"\vSCOPE_WORLD\x10\x01*U\n" +
	"\x05Level\x12\x13\n" +
	"\x0fLEVEL_ANONYMOUS\x10\x00\x12\x13\n" +
	"\x0fLEVEL_SIGNED_IN\x10\x01\x12\x11\n" +
	"\rLEVEL_BUILDER\x10\x02\x12\x0f\n" +
	"\vLEVEL_ADMIN\x10\x03B<Z:github.com/sulram/planet/server/internal/protocol;protocolb\x06proto3"

var (
	file_planet_v1_world_proto_rawDescOnce sync.Once
	file_planet_v1_world_proto_rawDescData []byte
)

func file_planet_v1_world_proto_rawDescGZIP() []byte {
	file_planet_v1_world_proto_rawDescOnce.Do(func() {
		file_planet_v1_world_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_planet_v1_world_proto_rawDesc), len(file_planet_v1_world_proto_rawDesc)))
	})
	return file_planet_v1_world_proto_rawDescData
}

var file_planet_v1_world_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_planet_v1_world_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_planet_v1_world_proto_goTypes = []any{
	(Body)(0),             // 0: planet.v1.Body
	(Gait)(0),             // 1: planet.v1.Gait
	(Scope)(0),            // 2: planet.v1.Scope
	(Level)(0),            // 3: planet.v1.Level
	(*Stance)(nil),        // 4: planet.v1.Stance
	(*Hello)(nil),         // 5: planet.v1.Hello
	(*Wear)(nil),          // 6: planet.v1.Wear
	(*Rename)(nil),        // 7: planet.v1.Rename
	(*Say)(nil),           // 8: planet.v1.Say
	(*ClientMessage)(nil), // 9: planet.v1.ClientMessage
	(*Recipe)(nil),        // 10: planet.v1.Recipe
	(*Peer)(nil),          // 11: planet.v1.Peer
	(*Welcome)(nil),       // 12: planet.v1.Welcome
	(*Joined)(nil),        // 13: planet.v1.Joined
	(*Left)(nil),          // 14: planet.v1.Left
	(*Wearing)(nil),       // 15: planet.v1.Wearing
	(*Renamed)(nil),       // 16: planet.v1.Renamed
	(*Moved)(nil),         // 17: planet.v1.Moved
	(*Stances)(nil),       // 18: planet.v1.Stances
	(*Said)(nil),          // 19: planet.v1.Said
	(*Refused)(nil),       // 20: planet.v1.Refused
	(*ServerMessage)(nil), // 21: planet.v1.ServerMessage
}
var file_planet_v1_world_proto_depIdxs = []int32{
	0,  // 0: planet.v1.Stance.body:type_name -> planet.v1.Body
	1,  // 1: planet.v1.Stance.gait:type_name -> planet.v1.Gait
	2,  // 2: planet.v1.Say.scope:type_name -> planet.v1.Scope
	5,  // 3: planet.v1.ClientMessage.hello:type_name -> planet.v1.Hello
	4,  // 4: planet.v1.ClientMessage.stance:type_name -> planet.v1.Stance
	6,  // 5: planet.v1.ClientMessage.wear:type_name -> planet.v1.Wear
	8,  // 6: planet.v1.ClientMessage.say:type_name -> planet.v1.Say
	7,  // 7: planet.v1.ClientMessage.rename:type_name -> planet.v1.Rename
	4,  // 8: planet.v1.Peer.stance:type_name -> planet.v1.Stance
	10, // 9: planet.v1.Welcome.recipe:type_name -> planet.v1.Recipe
	11, // 10: planet.v1.Welcome.peers:type_name -> planet.v1.Peer
	3,  // 11: planet.v1.Welcome.level:type_name -> planet.v1.Level
	11, // 12: planet.v1.Joined.peer:type_name -> planet.v1.Peer
	4,  // 13: planet.v1.Moved.stance:type_name -> planet.v1.Stance
	17, // 14: planet.v1.Stances.moved:type_name -> planet.v1.Moved
	2,  // 15: planet.v1.Said.scope:type_name -> planet.v1.Scope
	4,  // 16: planet.v1.Said.stance:type_name -> planet.v1.Stance
	12, // 17: planet.v1.ServerMessage.welcome:type_name -> planet.v1.Welcome
	13, // 18: planet.v1.ServerMessage.joined:type_name -> planet.v1.Joined
	14, // 19: planet.v1.ServerMessage.left:type_name -> planet.v1.Left
	18, // 20: planet.v1.ServerMessage.stances:type_name -> planet.v1.Stances
	15, // 21: planet.v1.ServerMessage.wearing:type_name -> planet.v1.Wearing
	20, // 22: planet.v1.ServerMessage.refused:type_name -> planet.v1.Refused
	19, // 23: planet.v1.ServerMessage.said:type_name -> planet.v1.Said
	16, // 24: planet.v1.ServerMessage.renamed:type_name -> planet.v1.Renamed
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_planet_v1_world_proto_init() }
func file_planet_v1_world_proto_init() {
	if File_planet_v1_world_proto != nil {
		return
	}
	file_planet_v1_world_proto_msgTypes[5].OneofWrappers = []any{
		(*ClientMessage_Hello)(nil),
		(*ClientMessage_Stance)(nil),
		(*ClientMessage_Wear)(nil),
		(*ClientMessage_Say)(nil),
		(*ClientMessage_Rename)(nil),
	}
	file_planet_v1_world_proto_msgTypes[17].OneofWrappers = []any{
		(*ServerMessage_Welcome)(nil),
		(*ServerMessage_Joined)(nil),
		(*ServerMessage_Left)(nil),
		(*ServerMessage_Stances)(nil),
		(*ServerMessage_Wearing)(nil),
		(*ServerMessage_Refused)(nil),
		(*ServerMessage_Said)(nil),
		(*ServerMessage_Renamed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_planet_v1_world_proto_rawDesc), len(file_planet_v1_world_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_planet_v1_world_proto_goTypes,
		DependencyIndexes: file_planet_v1_world_proto_depIdxs,
		EnumInfos:         file_planet_v1_world_proto_enumTypes,
		MessageInfos:      file_planet_v1_world_proto_msgTypes,
	}.Build()
	File_planet_v1_world_proto = out.File
	file_planet_v1_world_proto_goTypes = nil
	file_planet_v1_world_proto_depIdxs = nil
}
