// The chat plugin's wire: what rides the core's envelope under the name
// `chat` (DECISIONS 69, 93). `say` goes up as a Say, `said` comes down as a
// Said. `bun run proto` generates Rust into the plugin's own src/gen and Go
// into server/internal/chat/wire.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: planet/chat/v1/chat.proto

package wire

import (
	protocol "github.com/sulram/planet/server/internal/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Who hears a line.
type Scope int32

const (
	// Everyone within `NearBlocks` of the speaker, on the same body.
	Scope_SCOPE_NEAR Scope = 0
	// Everyone in the world, on every body.
	Scope_SCOPE_WORLD Scope = 1
)

// Enum value maps for Scope.
var (
	Scope_name = map[int32]string{
		0: "SCOPE_NEAR",
		1: "SCOPE_WORLD",
	}
	Scope_value = map[string]int32{
		"SCOPE_NEAR":  0,
		"SCOPE_WORLD": 1,
	}
)

func (x Scope) Enum() *Scope {
	p := new(Scope)
	*p = x
	return p
}

func (x Scope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Scope) Descriptor() protoreflect.EnumDescriptor {
	return file_planet_chat_v1_chat_proto_enumTypes[0].Descriptor()
}

func (Scope) Type() protoreflect.EnumType {
	return &file_planet_chat_v1_chat_proto_enumTypes[0]
}

func (x Scope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Scope.Descriptor instead.
func (Scope) EnumDescriptor() ([]byte, []int) {
	return file_planet_chat_v1_chat_proto_rawDescGZIP(), []int{0}
}

// A line of chat. Relayed to everyone in scope, the speaker included, and
// never stored. Dropped, and nobody told, past the plugin's length and rate
// limits: a UI holds the same limits so a person never meets them.
type Say struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Scope Scope                  `protobuf:"varint,1,opt,name=scope,proto3,enum=planet.chat.v1.Scope" json:"scope,omitempty"`
	// At most 500 characters. May be empty when `here` is set.
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// Share where you stand: the server fills Said.stance from the stance it
	// holds, so a client cannot claim to stand where it does not.
	Here          bool `protobuf:"varint,3,opt,name=here,proto3" json:"here,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Say) Reset() {
	*x = Say{}
	mi := &file_planet_chat_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Say) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Say) ProtoMessage() {}

func (x *Say) ProtoReflect() protoreflect.Message {
	mi := &file_planet_chat_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Say.ProtoReflect.Descriptor instead.
func (*Say) Descriptor() ([]byte, []int) {
	return file_planet_chat_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *Say) GetScope() Scope {
	if x != nil {
		return x.Scope
	}
	return Scope_SCOPE_NEAR
}

func (x *Say) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Say) GetHere() bool {
	if x != nil {
		return x.Here
	}
	return false
}

// A line someone said, the receiver's own included.
type Said struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Session uint32                 `protobuf:"varint,1,opt,name=session,proto3" json:"session,omitempty"`
	Scope   Scope                  `protobuf:"varint,2,opt,name=scope,proto3,enum=planet.chat.v1.Scope" json:"scope,omitempty"`
	Text    string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	// Where the speaker stood, when they shared it. Absent otherwise.
	Stance        *protocol.Stance `protobuf:"bytes,4,opt,name=stance,proto3" json:"stance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Said) Reset() {
	*x = Said{}
	mi := &file_planet_chat_v1_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Said) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Said) ProtoMessage() {}

func (x *Said) ProtoReflect() protoreflect.Message {
	mi := &file_planet_chat_v1_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Said.ProtoReflect.Descriptor instead.
func (*Said) Descriptor() ([]byte, []int) {
	return file_planet_chat_v1_chat_proto_rawDescGZIP(), []int{1}
}

func (x *Said) GetSession() uint32 {
	if x != nil {
		return x.Session
	}
	return 0
}

func (x *Said) GetScope() Scope {
	if x != nil {
		return x.Scope
	}
	return Scope_SCOPE_NEAR
}

func (x *Said) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Said) GetStance() *protocol.Stance {
	if x != nil {
		return x.Stance
	}
	return nil
}

var File_planet_chat_v1_chat_proto protoreflect.FileDescriptor

const file_planet_chat_v1_chat_proto_rawDesc = "" +
	"\n" +
	"\x19planet/chat/v1/chat.proto\x12\x0eplanet.chat.v1\x1a\x15planet/v1/world.proto\"Z\n" +
	"\x03Say\x12+\n" +
	"\x05scope\x18\x01 \x01(\x0e2\x15.planet.chat.v1.ScopeR\x05scope\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x12\n" +
	"\x04here\x18\x03 \x01(\bR\x04here\"\x8c\x01\n" +
	"\x04Said\x12\x18\n" +
	"\asession\x18\x01 \x01(\rR\asession\x12+\n" +
	"\x05scope\x18\x02 \x01(\x0e2\x15.planet.chat.v1.ScopeR\x05scope\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12)\n" +
	"\x06stance\x18\x04 \x01(\v2\x11.planet.v1.StanceR\x06stance*(\n" +
	"\x05Scope\x12\x0e\n" +
	"\n" +
	"SCOPE_NEAR\x10\x00\x12\x0f\n" +
	"\vSCOPE_WORLD\x10\x01B9Z7github.com/sulram/planet/server/internal/chat/wire;wireb\x06proto3"

var (
	file_planet_chat_v1_chat_proto_rawDescOnce sync.Once
	file_planet_chat_v1_chat_proto_rawDescData []byte
)

func file_planet_chat_v1_chat_proto_rawDescGZIP() []byte {
	file_planet_chat_v1_chat_proto_rawDescOnce.Do(func() {
		file_planet_chat_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_planet_chat_v1_chat_proto_rawDesc), len(file_planet_chat_v1_chat_proto_rawDesc)))
	})
	return file_planet_chat_v1_chat_proto_rawDescData
}

var file_planet_chat_v1_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_planet_chat_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_planet_chat_v1_chat_proto_goTypes = []any{
	(Scope)(0),              // 0: planet.chat.v1.Scope
	(*Say)(nil),             // 1: planet.chat.v1.Say
	(*Said)(nil),            // 2: planet.chat.v1.Said
	(*protocol.Stance)(nil), // 3: planet.v1.Stance
}
var file_planet_chat_v1_chat_proto_depIdxs = []int32{
	0, // 0: planet.chat.v1.Say.scope:type_name -> planet.chat.v1.Scope
	0, // 1: planet.chat.v1.Said.scope:type_name -> planet.chat.v1.Scope
	3, // 2: planet.chat.v1.Said.stance:type_name -> planet.v1.Stance
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_planet_chat_v1_chat_proto_init() }
func file_planet_chat_v1_chat_proto_init() {
	if File_planet_chat_v1_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_planet_chat_v1_chat_proto_rawDesc), len(file_planet_chat_v1_chat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_planet_chat_v1_chat_proto_goTypes,
		DependencyIndexes: file_planet_chat_v1_chat_proto_depIdxs,
		EnumInfos:         file_planet_chat_v1_chat_proto_enumTypes,
		MessageInfos:      file_planet_chat_v1_chat_proto_msgTypes,
	}.Build()
	File_planet_chat_v1_chat_proto = out.File
	file_planet_chat_v1_chat_proto_goTypes = nil
	file_planet_chat_v1_chat_proto_depIdxs = nil
}
