// The plugins a version carries, from plugins.json into each toolchain's own
// registry (DECISIONS 88): crates/plugins for the client, the Go package
// server/internal/plugins for the server, and the web front end's list. A
// plugin enters each registry for the half of it that exists. All of it is
// committed, so building needs no generator; changing the config does.
//   bun run plugins
import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { $ } from 'bun';
import { plugins, ROOT } from './lib';

$.cwd(ROOT);
const listed = plugins();
for (const { name } of listed) {
	// A name is the word before the dot in a command: `chat.say`.
	if (!/^[a-z_]+$/.test(name)) throw new Error(`plugins.json: "${name}" is no plugin name (a to z and _)`);
	if (name === 'plugins' || name === 'plugin') throw new Error(`plugins.json: "${name}" is the registry's own name`);
}
const write = (path: string, text: string) => {
	mkdirSync(`${ROOT}/${path.slice(0, path.lastIndexOf('/'))}`, { recursive: true });
	writeFileSync(`${ROOT}/${path}`, text);
};

// The client: a crate that depends on each plugin's crate.
const crates = listed.filter(({ name }) => existsSync(`${ROOT}/crates/${name}/Cargo.toml`));
write(
	'crates/plugins/Cargo.toml',
	`# Generated by \`bun run plugins\` from plugins.json: edit the config, never this file.
[package]
name = "plugins"
description = "The plugins this version carries, in the order the config lists them."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
client.workspace = true
${crates.map(({ name }) => `${name} = { path = "../${name}" }`).join('\n')}

[lints]
workspace = true
`
);
write(
	'crates/plugins/src/lib.rs',
	`//! The plugins this version carries, in the order the config lists them
//! (DECISIONS 88). A shell plugs each one into its client.
//!
//! Generated by \`bun run plugins\` from plugins.json: edit the config, never
//! this file.

/// Every plugin of the version, ready to plug in.
pub fn all() -> Vec<Box<dyn client::Plugin>> {
    vec![${crates.map(({ name }) => `${name}::plugin()`).join(', ')}]
}
`
);
await $`cargo fmt -p plugins`;

// The server: a package that imports each plugin's package.
const packages = listed.filter(({ name }) => {
	const dir = `${ROOT}/server/internal/${name}`;
	return existsSync(dir) && readdirSync(dir).some((file) => file.endsWith('.go'));
});
write(
	'server/internal/plugins/plugins.go',
	`// Code generated by \`bun run plugins\` from plugins.json. DO NOT EDIT.

// Package plugins is the plugins this version carries, in the order the
// config lists them (DECISIONS 88).
package plugins

import (
${[...packages.map(({ name }) => `\t"github.com/sulram/planet/server/internal/${name}"`), '\t"github.com/sulram/planet/server/internal/world"'].sort().join('\n')}
)

// All is every plugin of the version, and whether a world starts with each
// on.
func All() []world.Installed {
	return []world.Installed{
${packages.map(({ name, on }) => `\t\t{Plugin: ${name}.New(), On: ${on}},`).join('\n')}
	}
}
`
);
await $`gofmt -w server/internal/plugins/plugins.go`;

// The web front end: a list of each plugin's own index.
const panels = listed.filter(({ name }) => existsSync(`${ROOT}/apps/web/src/lib/plugins/${name}/index.ts`));
write(
	'apps/web/src/lib/plugins/index.ts',
	`// The plugins this version carries, in the order the config lists them
// (DECISIONS 88). The stage mounts the ones a world says are on.
//
// Generated by \`bun run plugins\` from plugins.json: edit the config, never
// this file.
import type { WebPlugin } from './plugin';
${panels.map(({ name }) => `import ${name} from './${name}';`).join('\n')}

export type { LayerProps, Seam, WebPlugin } from './plugin';

export const plugins: readonly WebPlugin[] = [${panels.map(({ name }) => name).join(', ')}];
`
);
console.log(`plugins -> crates/plugins, server/internal/plugins, apps/web/src/lib/plugins (${listed.map(({ name }) => name).join(', ')})`);
