// The plugins a version carries, from plugins.json into each toolchain's own
// registry (DECISIONS 88): crates/plugins-client for the engine,
// crates/plugins-world for the server's module, the web front end's list and
// buf's list of schemas. A plugin is the folder plugins/<name>/ (DECISIONS 100,
// 101) and enters each registry for the part of it that exists. All of it is
// committed, so building needs no generator; changing the config does.
//   bun run plugins
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { $ } from 'bun';
import { plugins, ROOT } from './lib';

$.cwd(ROOT);
const listed = plugins();
for (const { name } of listed) {
	// A name is the word before the dot in a command: `chat.say`.
	if (!/^[a-z_]+$/.test(name)) throw new Error(`plugins.json: "${name}" is no plugin name (a to z and _)`);
	// `plugins-client` and `plugins-world` are the registries' own crates.
	if (name === 'plugins' || name === 'plugin') throw new Error(`plugins.json: "${name}" is the registry's own name`);
	if (!existsSync(`${ROOT}/plugins/${name}`)) throw new Error(`plugins.json: "${name}" has no folder at plugins/${name}/`);
}
const write = (path: string, text: string) => {
	mkdirSync(dirname(`${ROOT}/${path}`), { recursive: true });
	writeFileSync(`${ROOT}/${path}`, text);
};

// The client: a crate that depends on each plugin's client half.
const clients = listed.filter(({ name }) => existsSync(`${ROOT}/plugins/${name}/client/Cargo.toml`));
write(
	'crates/plugins-client/Cargo.toml',
	`# Generated by \`bun run plugins\` from plugins.json: edit the config, never this file.
[package]
name = "plugins-client"
description = "The client halves of the plugins this version carries, in the order the config lists them."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
client.workspace = true
${clients.map(({ name }) => `${name}-client = { path = "../../plugins/${name}/client" }`).join('\n')}

[lints]
workspace = true
`
);
write(
	'crates/plugins-client/src/lib.rs',
	`//! The client halves of the plugins this version carries, in the order the
//! config lists them (DECISIONS 88). A shell plugs each one into its client.
//!
//! Generated by \`bun run plugins\` from plugins.json: edit the config, never
//! this file.

/// Every plugin of the version, ready to plug in.
pub fn all() -> Vec<Box<dyn client::Plugin>> {
    vec![${clients.map(({ name }) => `${name}_client::plugin()`).join(', ')}]
}
`
);

// The server's module: a crate that depends on each plugin's world half, and
// says whether a world starts with it on.
const worlds = listed.filter(({ name }) => existsSync(`${ROOT}/plugins/${name}/world/Cargo.toml`));
write(
	'crates/plugins-world/Cargo.toml',
	`# Generated by \`bun run plugins\` from plugins.json: edit the config, never this file.
[package]
name = "plugins-world"
description = "The world halves of the plugins this version carries, in the order the config lists them."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
world.workspace = true
${worlds.map(({ name }) => `${name}-world = { path = "../../plugins/${name}/world" }`).join('\n')}

[lints]
workspace = true
`
);
write(
	'crates/plugins-world/src/lib.rs',
	`//! The world halves of the plugins this version carries, in the order the
//! config lists them, each with whether a world starts with it on
//! (DECISIONS 88, 99). The server's module hosts them.
//!
//! Generated by \`bun run plugins\` from plugins.json: edit the config, never
//! this file.

use world::Installed;

/// Every world half of the version, ready to host.
pub fn all() -> Vec<Installed> {
    vec![
${worlds.map(({ name, on }) => `        Installed {\n            plugin: ${name}_world::plugin(),\n            on: ${on},\n        },`).join('\n')}
    ]
}
`
);
await $`cargo fmt -p plugins-client -p plugins-world`;

// The web front end: a list of each plugin's panel, a package of the Bun
// workspace that the app depends on.
const panels = listed.filter(({ name }) => existsSync(`${ROOT}/plugins/${name}/web/index.ts`));
const json = (path: string) => JSON.parse(readFileSync(`${ROOT}/${path}`, 'utf8')) as { name?: string; dependencies?: Record<string, string> };
const web = json('apps/web/package.json');
for (const { name } of panels) {
	const pkg = `@planet/plugin-${name}`;
	const manifest = `plugins/${name}/package.json`;
	if (!existsSync(`${ROOT}/${manifest}`) || json(manifest).name !== pkg) {
		throw new Error(`${manifest}: a panel is the package "${pkg}", with "." exported as ./web/index.ts`);
	}
	if (!web.dependencies?.[pkg]) throw new Error(`apps/web/package.json: add "${pkg}": "workspace:*" to dependencies, then \`bun install\``);
}
write(
	'apps/web/src/lib/plugins/index.ts',
	`// The plugins this version carries, in the order the config lists them
// (DECISIONS 88). The stage mounts the ones a world says are on.
//
// Generated by \`bun run plugins\` from plugins.json: edit the config, never
// this file.
import type { WebPlugin } from './plugin';
${panels.map(({ name }) => `import ${name} from '@planet/plugin-${name}';`).join('\n')}

export type { LayerProps, Seam, WebPlugin } from './plugin';

export const plugins: readonly WebPlugin[] = [${panels.map(({ name }) => name).join(', ')}];
`
);

// The schemas: the core's module, and the one of each plugin that has a wire.
const wires = listed.filter(({ name }) => existsSync(`${ROOT}/plugins/${name}/wire`));
write(
	'buf.yaml',
	`# Generated by \`bun run plugins\` from plugins.json: edit the config, never
# this file. The schemas, the core's and each plugin's own: \`bun run proto\`
# generates from them, and \`buf lint\` keeps them in the standard style.
version: v2
modules:
  - path: proto
${wires.map(({ name }) => `  - path: plugins/${name}/wire`).join('\n')}
lint:
  use:
    - STANDARD
  except:
    # A zero value here is a chosen default, not an unspecified one: an absent
    # body is the planet and an absent gait is standing still.
    - ENUM_ZERO_VALUE_SUFFIX
breaking:
  use:
    - FILE
`
);
console.log(`plugins -> crates/plugins-client, crates/plugins-world, apps/web/src/lib/plugins, buf.yaml (${listed.map(({ name }) => name).join(', ')})`);
