// The plugins this version carries, in the order the config lists them
// (DECISIONS 88). The stage mounts the ones a world says are on.
//
// Generated by `bun run plugins` from plugins.json: edit the config, never
// this file.
import type { WebPlugin } from './plugin';
import chat from './chat';

export type { LayerProps, Seam, WebPlugin } from './plugin';

export const plugins: readonly WebPlugin[] = [chat];
